### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1003]
Looks like `openai.Timeout` is not an Exception. Example incorrect usage [link](https://github.com/Codium-ai/pr-agent/blob/55a82382efe91a6432630ec12b7feb1192692bc0/pr_agent/algo/ai_handlers/litellm_ai_handler.py#L146)

>   File "C:\git\mrichar2_tools\pr-agent\pr_agent\algo\ai_handlers\litellm_ai_handler.py", line 146, in chat_completion
>     except (openai.APIError, openai.Timeout) as e:
> TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by mrT23** [comment]
Validate your openai pip version

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/754af6ca-1b1c-4895-b0fb-49617e14b733)

**Comment by MarkRx** [comment]
> openai 1.35.1
> httpx 0.27.0

The [Timeout](https://github.com/encode/httpx/blob/master/httpx/_config.py#L196) class comes from httpx/_config.py and does not inherit from Exception

`class Timeout:`

**Comment by theosyslack** [comment]
I'm getting a similar issue when attempting to set the following environment variables in the latest docker build. 

```
- `OPENAI.KEY="$OPEN_AI_TOKEN"`
- `CONFIG.GIT_PROVIDER="gitlab"`
- `GITLAB.PERSONAL_ACCESS_TOKEN="$GITLAB_TOKEN"`
- `GITLAB.URL="$SELF_HOSTED_GITLAB_URL"`
- `OPENAI.API_TYPE="azure"`
- `OPENAI.KEY="$OPEN_AI_TOKEN"`
- ``OPENAI.API_BASE=$AZURE_INSTANCE_URL`
```

**Comment by mrT23** [comment]
ok, i will remove this exception
