### ISSUE TITLE
[Feature Request] Convert logging configuration to use loguru-config

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1007]
The current logging configuration is [in code](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/log/__init__.py). This does not provide the flexibility to modify logging without requiring forking and making code changes.

The [loguru-config](https://github.com/erezinman/loguru-config) module allows for configuring loggers using a yaml or json file. Logging should be switched over to use this with a default file that emulates the current logging settings.

**Comment by mrT23** [comment]
I don't see this as a feature that would be relevant to many other users.
These micro customizations can clog and overload a repo.
Hence, they are suitable for a **fork**

**Comment by MarkRx** [comment]
It's useful to allow tuning the log levels on different loggers / packages. Additionally, in an enterprise environment it's not uncommon to be able to customize logging formats and log rotation settings so log ingesters (such as Splunk) can better parse them.
