### ISSUE TITLE
The docker build target must be gitlab_webhook for local gitlab install

### ISSUE THREAD

**Issue by ocroz** [Codium-ai/pr-agent#1010]
Thanks to https://github.com/Codium-ai/pr-agent/pull/682, I could fix my local GitLab installation with this docker build command:
```bash
docker build . -t pr-agent:4ab747d_gitlab --target gitlab_webhook -f docker/Dockerfile
```
The target must be `gitlab_webhook` when building the Docker image.
However, I cannot find this information in the current documentation anymore.
Could you please re-add this important information?

**Comment by mrT23** [comment]
welcome to open a PR to update the relevant docs
