### ISSUE TITLE
Gitea Support

### ISSUE THREAD

**Issue by narachen** [Codium-ai/pr-agent#1024]
Hello ,

I really like your project.  Do you have any plans to release an agent that supports  Gitea repo?

Best Regards

**Comment by mrT23** [comment]
Hi @narachen 
We are open to community contribution for this framework, as was done for other frameworks.

**Comment by docker-mobile** [comment]
@CodiumAI-Agent /generate-labels

**Comment by mrT23** [comment]
closing this issue.
As i said, community contribution is welcomed here

**Comment by nightzjp** [comment]
请问现在是否支持gitea呢
