### ISSUE TITLE
Self-host Github App is not working with Github Enterprise Server

### ISSUE THREAD

**Issue by bobbyc** [Codium-ai/pr-agent#1036]
I encounter an issue with Github Enterprise Server, where the webhook of pull_request cannot be parsed by github_provider.

my webhook: 

"pull_request": {"url": "https://{netloc}/api/v3/repos/{org}/{repo}/pulls/883"}

bug location:

https://github.com/Codium-ai/pr-agent/blob/228ceff3a66c7d99d6a43d304f60e2871f66ac6f/pr_agent/git_providers/github_provider.py#L617

Is it possible to fix this, and compatible with Github Enterprise Server?

**Comment by mrT23** [comment]
(1) In pr-agent pro we made the needed changes to support GitHub enterprise
https://pr-agent-docs.codium.ai/overview/pr_agent_pro/

(2) the change you describe is not enough to do that. more adaptations are needed for the app.

(3) If you want to **try** pr-agent on a github enterprise environment, you have two options:
- CLI (which is supported)
- 2 weeks of free trial with pr-agent pro

After that, if you find value in pr-agent, you should buy it. Especially In the GitHub enterprise environment, which is a highly commercial environment used by large corporations.

(4) having said that, you can always make code changes on your local fork


all the best
