### ISSUE TITLE
[Feature Request] Support OpenAI seed parameter

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1057]
The [seed](https://cookbook.openai.com/examples/reproducible_outputs_with_the_seed_parameter) parameter can be used to make the LLM more deterministic on newer OpenAI API versions. See [blog](https://cookbook.openai.com/examples/reproducible_outputs_with_the_seed_parameter) for more details.

I propose either
1. A hard coded seed value is passed in to every request *and then logged* (when the API supports it) or
2. A random seed value is passed in to every request *and then logged* (when the API supports it)

Having access to the seed makes reproducing results easier which in-turn makes debugging and tuning queries easier.

**Comment by mrT23** [comment]
Thats a good idea.
i will look into that
(it requires also making the temperature adaptable)

**Comment by mrT23** [comment]
It seems seed is not a working feature yet:

https://community.openai.com/t/seed-param-and-reproducible-output-do-not-work/487245/1

but at least pr-agent will have an infrastructure for that
https://github.com/Codium-ai/pr-agent/pull/1063
