### ISSUE TITLE
Bitbucket Server link to lines in file missing

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1058]
The [bitbucket_server_provider](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/git_providers/bitbucket_server_provider.py) is missing the implementation for [get_line_link](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/git_providers/git_provider.py#L137C9-L137C22). As a result generated links only refer back to the overview of the PR.

I will create a PR to fix this.

**Comment by mrT23** [comment]
ok

make sure first you integrate this:
https://github.com/Codium-ai/pr-agent/pull/1059
to your PR, and make sure they are compatible

**Comment by mrT23** [comment]
merged
