### ISSUE TITLE
BitBucket Server commitable code suggestions does not work with multi-line comments

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1076]
BitBucket Server does not support multi-line code suggestions ([BSERV-4553](https://jira.atlassian.com/browse/BSERV-4553)). When commitable_code_suggestions is enabled this results in inaccurate suggestions. When the inaccurate suggestion is applied, the first line is modified to be the new content while subsequent lines remain. As a result the final change ends up containing duplicate code.

I propose for BitBucket Server suggestions that cover multiple lines be handled as regular comments even if commitable_code_suggestions is enabled. The multi-line limitation should then be documented.

Currently commitable_code_suggestions shouldn't be used with BitBucket server due to the problem described in this issue.

**Comment by mrT23** [comment]
cc
@taisyalobanov

**Comment by MarkRx** [comment]
Literally hours after creating this issue Atlassian updated the **10 year old** [BSERV-4553](https://jira.atlassian.com/browse/BSERV-4553) ticket indicating it is planned on the [roadmap](https://www.atlassian.com/roadmap/data-center?status=comingSoon&product=bitbucket) for Q3 2024.

I still think the workaround should be put in place until that is released since it should be relatively easy to change.

**Comment by mrT23** [comment]
merged
