### ISSUE TITLE
Multiple help texts added to PR description when marker enabled.

### ISSUE THREAD

**Issue by akshat-ema** [Codium-ai/pr-agent#1077]
Below is a screenshot of PR description. On every push to the PR it is adding the same help text each time. Can we just add it once when its missing and skip at other times. I am using github_app with description markers enabled in PR.

![image](https://github.com/user-attachments/assets/a003273f-c5df-4af7-bb5e-0ed1ebada01e)

**Comment by mrT23** [comment]
- you are using a very "unique" settings - markers + enable_help_text + describe-on-each-push.
none of them is enabled by default.

- I don't understand what is the meaning of `markers` + `describe-on-each-push` (on the next push, you won't have markers).

- in any case, a simple solution is to set:
```
[pr_description]
enable_help_text=false
```
If you are using such advanced options, I think you could do without the help text. it would also clean up a bit your description

**Comment by akshat-ema** [comment]
TYSM
