### ISSUE TITLE
Open source Fine-tuning Benchmark

### ISSUE THREAD

**Issue by dl-sdu** [Codium-ai/pr-agent#1084]
Hi Codium,
    This project is so great for pull request reviewing. I notice that LLM got huge improvement  after finetuning in doc. Would you consider open source your finetune data in future? Thanks a lot!

**Comment by mrT23** [comment]
I don't see us publishing the training dataset. Almost no one does that, and for a good reason - it's a commercial proprietary

I do hope that we will be able to publish the code models one day. We are not there yey, still due to proprietary limitations, but maybe in the future
