### ISSUE TITLE
Support Google AI Studio

### ISSUE THREAD

**Issue by yu-iskw** [Codium-ai/pr-agent#1085]
Currently, it already supports Google Cloud Vertex AI. Google AI Stduio is another option to use the Gemini family. It might be another options for AI-powered development. 

- https://ai.google.dev/aistudio
- https://ai.google.dev/pricing

**Comment by mrT23** [comment]
We are open to PRs on this.
syntax should be similar, using litellm

**Comment by mrT23** [comment]
review other provider (liker vertexAI) and litellm documentation, and do the the same

https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/ai_handlers/litellm_ai_handler.py
