### ISSUE TITLE
Security vulnerability in python 3.10 base docker image, upgrade to python 3.12

### ISSUE THREAD

**Issue by pc-bob** [Codium-ai/pr-agent#1086]
There is a security vulnerability in the 3.10 python base image: 

<img width="950" alt="Screenshot 2024-08-01 at 2 24 04 PM" src="https://github.com/user-attachments/assets/0fa28401-103e-4ecc-b927-3b17635373cb">

The same vulnerability exists in python 3.11:

<img width="940" alt="Screenshot 2024-08-01 at 2 24 36 PM" src="https://github.com/user-attachments/assets/cf501f06-55ec-4e2b-949c-6f0ca2c7d099">

But it has been fixed in python 3.12:

<img width="737" alt="Screenshot 2024-08-01 at 2 25 20 PM" src="https://github.com/user-attachments/assets/0c1d3d62-e614-436c-9c8a-2f1997dd7e64">

Is it possible to update the Python base images used to 3.12?

**Comment by pc-bob** [comment]
Looks to be addressed in https://github.com/Codium-ai/pr-agent/pull/1091, just need new docker image published

**Comment by mrT23** [comment]
a docker was released
