### ISSUE TITLE
description feature - YAML parsing fails when filename starts with underscore character

### ISSUE THREAD

**Issue by Qubhis** [Codium-ai/pr-agent#1094]
Hi team,
the PR-Agent is great and I'm using it for making descriptions and making reviews. I'm working with frameworks where some files and folders needs to have an underscore as a leading character. For example `_i18n`. Unfortunately, yaml parser fails when such filename is not wrapped in quotes. 

I've personally bumped into that issue when using description feature
https://github.com/Codium-ai/pr-agent/blob/8ec1fb593770cbeaacc427c13f49a3c78d85e116/pr_agent/settings/pr_description_prompts.toml#L41

and my local fix was just edit the Field.description with `"the relevant file full path in between quotes. E.g. '_i18n/i18n.properties'"`

**Comment by mrT23** [comment]
thanks for the feedback. We will review that scenario
(It seems that in contrast to my intuition, it is legal for a file to start with '_'

![image](https://github.com/user-attachments/assets/55baf978-6280-4817-9623-25b15200bda5)

**Comment by mrT23** [comment]
@Qubhis 
Why would the YAML parser fail (without quotes) ? Its a valid YAML:


`- filename: _i18n/i18n.propertie
`

![image](https://github.com/user-attachments/assets/e0c90b01-e430-4939-b2cd-54321c4950bd)

**Comment by Qubhis** [comment]
@mrT23 I'm trying to replicate the parsing issue, but I'm not able to reproduce it. It seems that the parser always returns a string value even with _i18n.

To be honest, I encountered that problem in April and only remembered it when I was updating to v0.23 this week. Since I'm unable to replicate the issue, I apologize if I wasted any of your time. Let's consider this issue closed.
