### ISSUE TITLE
Support for new cheaper GPT-4o model `gpt-4o-2024-08-06`

### ISSUE THREAD

**Issue by ChrisWiles** [Codium-ai/pr-agent#1097]
OpenAI just released a new GPT-4o model today, and it's much cheaper: can save 50% on inputs and 33% on outputs compared to the previous version. Can we add support for it?

> By switching to the new gpt-4o-2024-08-06, developers save 50% on inputs ($2.50/1M input tokens) and 33% on outputs ($10.00/1M output tokens) compared to gpt-4o-2024-05-13.
https://openai.com/index/introducing-structured-outputs-in-the-api/

**Comment by mrT23** [comment]
support was added here. thanks to @KennyDizi 
https://github.com/Codium-ai/pr-agent/pull/1098

Regarding making it the _default_ turbo model, I want to benchmark it first. make sure there is no suprises

**Comment by KennyDizi** [comment]
> OpenAI just released a new GPT-4o model today, and it's much cheaper: can save 50% on inputs and 33% on outputs compared to the previous version. Can we add support for it?
> 
> > By switching to the new gpt-4o-2024-08-06, developers save 50% on inputs ($2.50/1M input tokens) and 33% on outputs ($10.00/1M output tokens) compared to gpt-4o-2024-05-13.
> > https://openai.com/index/introducing-structured-outputs-in-the-api/

That's true, my perfect configuration is
```
[config]
model="gpt-4o-mini-2024-07-18"
model_turbo="gpt-4o-2024-08-06"
fallback_models=["anthropic/claude-3-5-sonnet-20240620"]
```

**Comment by apache829** [comment]
Does it support the claimed 16,384 token output?

**Comment by mrT23** [comment]
@apache829 yes
