### ISSUE TITLE
Clarification of Documentation for Integration with a GitLab Webhook

### ISSUE THREAD

**Issue by ascieux-soprasteria** [Codium-ai/pr-agent#1099]
Hello,

I have deployed codium-ai/pr-agent in self-hosted mode on an Azure machine via Docker to use it with an on-premise corporate GitLab instance.

The GitLab webhooks were not working, returning a "405 Method not allowed" error similar to [456](https://github.com/Codium-ai/pr-agent/issues/456) and [812](https://github.com/Codium-ai/pr-agent/issues/812). 

However, I was using the correct image ````codiumai/pr-agent:gitlab_webhook```` and the [solution](https://github.com/Codium-ai/pr-agent/issues/812#issuecomment-2046167097) provided there is for GitHub.

The [documentation for pr-agent GitLab integration](https://pr-agent-docs.codium.ai/installation/gitlab/) mentions "Set the URL to the URL of your app's server", which results in the same HTTP error "405 Method not allowed".

Could you please update the documentation to specify that the URL to configure for GitLab should be ````http[s]://<PR_AGENT_IP>/webhook```` and not ````http[s]://<PR_AGENT_IP>```` as might be inferred from "URL of your app's server"?

**Comment by mrT23** [comment]
you are welcome to open a PR updating this
https://github.com/Codium-ai/pr-agent/blob/main/docs/docs/installation/gitlab.md#run-a-gitlab-webhook-server
(or any other relevant doc)

**Comment by ascieux-soprasteria** [comment]
Hi,
Thank you for the docs pointer, I have created [PR 1100](https://github.com/Codium-ai/pr-agent/pull/1100) accordingly.

**Comment by mrT23** [comment]
merged 👍
