### ISSUE TITLE
Github actions error

### ISSUE THREAD

**Issue by shashank42** [Codium-ai/pr-agent#111]
openai.error.InvalidRequestError: The model: `gpt-4-0613` does not exist

**Comment by coditamar** [comment]
you need to have access to `gpt-4-0613`
https://openai.com/blog/function-calling-and-other-api-updates
otherwise, you can change it in the 'pr_agent/settings/configuration.toml'

or are you requesting it to be configurable somehow differently?

**Comment by okotek** [comment]
Can you try again with the current main branch, we are dealing with such errors by falling back to gpt-3.5-turbo

**Comment by mrT23** [comment]
i believe this issue was resolved

**Comment by triptu** [comment]
is it possible to pass this option in anyway while using the Github Action?

**Comment by triptu** [comment]
also there seems to be a bug. the fallback model was correctly used, but the action still failed.

<img width="885" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/16299282/3b731f8f-606a-49a5-952f-0f3d94bf1e46">
