### ISSUE TITLE
Github Base URL not being passed correctly throughout class

### ISSUE THREAD

**Issue by squinn1** [Codium-ai/pr-agent#1120]
Hi, 

Currently, pr-agent does not support a self hosted github instance. while you are able to pass a github.base_url via config, there are a couple of instances of the base_url being hard coded through the class. For example: 

- https://github.com/Codium-ai/pr-agent/blob/ef37271ce943803a19cbe7d796e1e480643d3229/pr_agent/git_providers/github_provider.py#L826 
- https://github.com/Codium-ai/pr-agent/blob/ef37271ce943803a19cbe7d796e1e480643d3229/pr_agent/git_providers/github_provider.py#L632

**Comment by squinn1** [comment]
Thanks for your reply @mrT23. 

This feature has been half implemented throughout the class with only a couple of hard coded references in the code. would you be willing to accept a PR to fix these changes? I have raised one here

https://github.com/Codium-ai/pr-agent/pull/1127

Thanks!

**Comment by mrT23** [comment]
closing as completed
