### ISSUE TITLE
max_context_tokens for pr_code_suggestions

### ISSUE THREAD

**Issue by r-ashraf** [Codium-ai/pr-agent#1140]
I am just wondering what is this set to 14000 while max_model_tokens = 32000 under config. while most new ai models nowadays support >100K context,
is it ok for me to change the max context token for "improve" case, Anything I need to know

**Comment by mrT23** [comment]
Your are welcome to change

Models do *support* large context, but the quality may degrade.
We limit the number of tokens (and enable multiple calls) trying to increase **quality**
But maybe you would find a better tradeoff
