### ISSUE TITLE
 Improve PR Description by Adding Links to File Diffs in Enhancement Section

### ISSUE THREAD

**Issue by arise-project** [Codium-ai/pr-agent#1146]
In the current GitLab pipeline, the 'describe' step generates a 'PR description' that includes an Enhancement section with details such as:

| BaseTestsGen.cs | Refactor BaseTestsGen and add CanonicalM class | +156/-329 |

where '+156/-329' added and removed lines in the diff, represented as . Currently, this information is presented as link to file in repository BaseTestsGen.cs.

Could it possible to enhance usability with change this links to the file diffs in the MR for Gitlab?
This improvement would allow users to quickly access and review the specific changes made to a file directly from the PR description, improving workflow efficiency.

**Comment by mrT23** [comment]
thanks, will look into this

seems like a bug
