### ISSUE TITLE
Hide or Mark Outdated PR Code Suggestions as Complete

### ISSUE THREAD

**Issue by arise-project** [Codium-ai/pr-agent#1147]
In the current workflow of Gitlab 'improve' pipeline, when a proposed PR Code Suggestion is implemented and the code is fixed accordingly, there is no clear indication or history in the PR to reflect that the suggestion has been addressed. PR Code Suggestions remain visible even after the suggested changes have been implemented, with no indication that they have been resolved.

Could you research possibility of I suggest implementing a feature to either?

1. Hide Outdated Code Suggestions: Automatically hide PR Code Suggestions that have been addressed and are no longer relevant.
2. Mark Suggestions as Complete: Alternatively, mark these suggestions as complete or resolved, providing a visual cue that the proposed changes have been implemented.

This improvement would make it easier to track which suggestions have been addressed, ensuring that PR reviews are more focused and that outdated suggestions do not clutter the review process.

**Comment by mrT23** [comment]
use pr-agent-pro
https://pr-agent-docs.codium.ai/overview/pr_agent_pro/


All of this has been addressed there to the highest details. In general, pr-agent-pro offers many advantages both for implementing suggestions, tracking them during PR, and getting post-process statistics.

https://github.com/Codium-ai/pr-agent/pull/1141#issuecomment-2288939477

---

![image](https://github.com/user-attachments/assets/b0d6be5f-623e-49d1-a206-77de163dfc59)

---

![image](https://github.com/user-attachments/assets/f21d0d9f-6451-4970-9d8d-f13f46fcd657)
