### ISSUE TITLE
Error: GitLabProvider.send_inline_comment() missing 1 required positional argument: 'original_suggestion'

### ISSUE THREAD

**Issue by minff** [Codium-ai/pr-agent#1149]
When I run the `review` command for Gitlab, got the following error **"GitLabProvider.send_inline_comment() missing 1 required positional argument: 'original_suggestion'"** . Any idea what went wrong ?

> $ python -m pr_agent.cli --pr_url="$MR_URL" review
> 2024-08-15 19:32:02.895 | INFO     | pr_agent.git_providers.gitlab_provider:get_diff_files:99 - Filtered out [ignore] files for merge request 41
> 2024-08-15 19:32:21.715 | INFO     | pr_agent.tools.pr_reviewer:run:107 - Reviewing PR: https://localhost:8080/test-repo/merge_requests/41 ...
> 2024-08-15 19:32:22.218 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:63 - PR main language: Python
> 2024-08-15 19:32:22.239 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:74 - Tokens: 26308, total tokens under limit: 32000, returning full diff.
> 2024-08-15 19:32:33.074 | INFO     | pr_agent.tools.pr_reviewer:set_review_labels:416 - Review labels are already set:
> ['Review effort [1-5]: 4', 'enhancement']
> 2024-08-15 19:32:33.867 | INFO     | pr_agent.git_providers.git_provider:publish_persistent_comment_full:171 - Persistent mode - updating comment https://localhost:8080/test-repo/-/merge_requests/41#note_8432540 to latest review message
> 2024-08-15 19:32:35.227 | ERROR    | pr_agent.tools.pr_reviewer:run:148 - Failed to review PR: GitLabProvider.send_inline_comment() missing 1 required positional argument: 'original_suggestion'

**Comment by mrT23** [comment]
should be fixed now

**Comment by minff** [comment]
the error is resolved. Thank you !
