### ISSUE TITLE
No eligible user found

### ISSUE THREAD

**Issue by aliavni** [Codium-ai/pr-agent#1158]
Hi Folks,

I installed the `CodiumAI PR-Agent Pro` app in one of my private repos. It works for other devs, reviews the PR, adds description etc.

But it never works for the PR that I create. For example, if I comment with `/review`, I get the following message:

```
PR-Agent was enabled for this repository, but no eligible user found. Please link your git user with your CodiumAI identity
```

Any idea why this might be happening?

**Comment by mrT23** [comment]
have you clicked the link and made sure you linked your github account ?

**Comment by aliavni** [comment]
@mrT23 yes. This is what I see:

<img width="983" alt="Screenshot 2024-08-19 at 1 35 11 PM" src="https://github.com/user-attachments/assets/1f1d11a5-1c46-48cb-84ed-7c702547a1eb">

**Comment by mrT23** [comment]
ok. Share an address of a pr URL so we can look at the logs.

Just making sure: you are a Pro user, and not just on a trial that ended ?

**Comment by aliavni** [comment]
That might be the case. I am not a Pro user. Here is the (private) URL https://github.com/thesunlitlive/backend/pull/31

**Comment by mrT23** [comment]
yes, thats what i see in the log:

![image](https://github.com/user-attachments/assets/b729e241-cc15-4e39-975e-5a4a89613352)

**Comment by aliavni** [comment]
Thanks. I am closing this issue

**Comment by ibukunoluwayomi** [comment]
The error message could be more helpful. Took me hours to realise this was the issue
