### ISSUE TITLE
[Question] When is the next release planned? 

### ISSUE THREAD

**Issue by squinn1** [Codium-ai/pr-agent#1162]
Hi, 
Just wanted an update on when the next release is planned? there's been some changes since the 0.23 release that I would like to test out. 

Thanks

**Comment by mrT23** [comment]
I think at the beginning of September.

But if you want now to work against an updated yet fixed version, just do this:

https://pr-agent-docs.codium.ai/installation/github/#run-as-a-github-action

![image](https://github.com/user-attachments/assets/54e71335-bb2e-46bd-a1d7-d998511981f2)

**Comment by mrT23** [comment]
new official version (v0.24) was releasd 
https://github.com/Codium-ai/pr-agent/releases/tag/v0.24
