### ISSUE TITLE
Default configuration.toml models

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1164]
Currently the `configuration.toml` defaults have the turbo model in "model" and the 4o non-turbo model in "model_turbo". Is this correct?

```
[config]
# models
model="gpt-4-turbo-2024-04-09"
model_turbo="gpt-4o-2024-08-06"
fallback_models=["gpt-4o-2024-05-13"]
```

https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L3-L4

**Comment by mrT23** [comment]
it is correct.
its openAI fault, they made a mess of the names

"gpt-4-turbo-2024-04-09" is currently the strongest (and slowest) model they have.
"gpt-4o-2024-08-06" is the mid-level model. lower quality, but faster, and less expensive
