### ISSUE TITLE
we will have to understand  architecture 

### ISSUE THREAD

**Issue by prasadnaikg-ldp** [Codium-ai/pr-agent#1178]
We have used this following pipeline and working fine .

we will have to understand its architecture also, like does it send our code to their server for analysis.
or how otherwise the analysis is happening ,
or is their code being fetched inside the docker container in pipeline

Run as a GitLab Pipeline[¶](https://pr-agent-docs.codium.ai/installation/gitlab/#run-as-a-gitlab-pipeline)
You can use a pre-built Action Docker image to run PR-Agent as a GitLab pipeline. This is a simple way to get started with PR-Agent without setting up your own server.

(1) Add the following file to your repository under .gitlab-ci.yml:

stages:
  - pr_agent

pr_agent_job:
  stage: pr_agent
  image: 
    name: codiumai/pr-agent:latest
    entrypoint: [""]
  script:
    - cd /app
    - echo "Running PR Agent action step"
    - export MR_URL="$CI_MERGE_REQUEST_PROJECT_URL/merge_requests/$CI_MERGE_REQUEST_IID"
    - echo "MR_URL=$MR_URL"
    - export gitlab__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN 
    - export config__git_provider="gitlab"
    - export openai__key=$OPENAI_KEY
    - python -m pr_agent.cli --pr_url="$MR_URL" describe
    - python -m pr_agent.cli --pr_url="$MR_URL" review
    - python -m pr_agent.cli --pr_url="$MR_URL" improve
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
This script will run PR-Agent on every new merge request. You can modify the rules section to run PR-Agent on different events. You can also modify the script section to run different PR-Agent commands, or with different parameters by exporting different environment variables.
(2) Add the following masked variables to your GitLab repository (CI/CD -> Variables):

GITLAB_PERSONAL_ACCESS_TOKEN: Your GitLab personal access token.

OPENAI_KEY: Your OpenAI key.

Note that if your base branches are not protected, don't set the variables as protected, since the pipeline will not have access to them.

**Comment by mrT23** [comment]
I don't understand your request. Use clearer language.

In any case, review our privacy policy
https://pr-agent-docs.codium.ai/overview/data_privacy/

**Comment by prasadnaikg-ldp** [comment]
Hi @mrT23, we have implemented the PR agent in GitLab via a pipeline, and I have a few questions regarding its architecture. Specifically, I'm curious about how the analysis is conducted. Does it send our code to their server for analysis, or is the analysis conducted within our Docker container in the pipeline? Alternatively, is their code fetched into our Docker container for the analysis?

**Comment by mrT23** [comment]
servers of who ?

**Comment by prasadnaikg-ldp** [comment]
Pr agent server
For instance, when we use the review command with the PR agent, I'm curious about the underlying process during the code review. Does it send our code to the PR agent server, or is the review conducted differently? An architectural overview of the workflow would greatly enhance our understanding.
