### ISSUE TITLE
[Feature Request] To allow to use .pr_agent.toml from the merge requests source branch

### ISSUE THREAD

**Issue by TzviCons** [Codium-ai/pr-agent#1183]
I"m currently trying out the agent for my repo and am reluctant to add files to the codebase before I'm certain they are helpful to the entire team. 

Using the .pr_agent.toml file in the MR's source branch will allow one to test changes in the agents behavior without needing to affect the main codebase in the master branch. 

Could this at least be added as a configurable feature `use_source_branch_settings_file=false` alongside the flag for `use_repo_settings_file=true` [here](https://github.com/Codium-ai/pr-agent/blob/7373ed36e6f1fd9232a8f8c8c09c2449cd89aae4/pr_agent/settings/configuration.toml#L14)?

**Comment by mrT23** [comment]
No. Its egg-and-chicken
Even if there was such a configuration (`use_source_branch_settings_file`), we would need to read it from a ... configuration file.

If you want to experiment with configurations before committing them (which is a reasonable demand), do online commenting:
https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#online-usage

PR-Agent pro user can also use wiki, which does not require committing:
https://pr-agent-docs.codium.ai/usage-guide/configuration_options/#wiki-configuration-file

**Comment by TzviCons** [comment]
@mrT23 Thanks for your prompt response and the tip. I'll use those for now but still feel it would beneficial to allow the branch config file to be used. 

I would disagree with the chicken-and-egg argument as there already is a precedent. Offering the `use_source_branch_settings_file` as a configuration should be no different than the existing `use_repo_settings_file` option. Certainly the `config.git_provider`, setting which is [in the config file](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L7) but needs to be set as environment variables. If this feature is non-intuitive, it could default to false and those that want it can set it to true in the repo main branch or in environment variables.

**Comment by mrT23** [comment]
if you feel this feature is needed, and gives you value over online commenting, I would accept a PR for it.

It needs to be accompanied by documentation update
