### ISSUE TITLE
force_timeout in litellm_ai_handler.py does not work

### ISSUE THREAD

**Issue by woung717** [Codium-ai/pr-agent#1187]
pr-agent uses litellm==1.43.13 in the main branch, and the force_timeout argument seems to be deprecated in acompletion and completion (sync function). So even though there is a config value "config.ai_timeout", it does not work. When I changed the config, the timeout is not applied.
https://github.com/Codium-ai/pr-agent/blob/97b48da03bcd4342f03bfa74c36b94f4c7d08283/pr_agent/algo/ai_handlers/litellm_ai_handler.py#L188-L195

It seems that they now support the timeout feature using the "timeout" parameter, so we need to change it to something like this.
```python
 kwargs = {
                "model": model,
                "deployment_id": deployment_id,
                "messages": messages,
                "temperature": temperature,
                "timeout": get_settings().config.ai_timeout,  # key is changed
                "api_base": self.api_base,
            }
``` 

LiteLLM timeout logic
https://github.com/BerriAI/litellm/blob/9c039a9064a5d91b356505db4736e84528a9db9f/litellm/main.py#L803-L811

HyeonUng

**Comment by mrT23** [comment]
you are welcome to open a PR to address this issue
