### ISSUE TITLE
Publish output being set to false still publishes if there are no code suggestions found for PR

### ISSUE THREAD

**Issue by AHancher2022** [Codium-ai/pr-agent#1188]
I noticed that if publish output is set to false, that if there are no code suggestions, it will still leave a comment on PRs. Similar to a issue submitted earlier this week. 

I will work on a quick change and get a PR in to fix the issue. It is happening on this [Line](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/tools/pr_code_suggestions.py#L114) in code suggestion and I am not sure about pr_reviewer but I can take a look in there as well to confirm.

**Comment by mrT23** [comment]
Its a bug.
you are welcome to open a PR to address this
