### ISSUE TITLE
Why the 0.24 release has ben retagged ? 

### ISSUE THREAD

**Issue by paolomainardi** [Codium-ai/pr-agent#1199]
I've just noticed that the 0.24 release has been recreated starting from the current main.
Is there a specific reason why a 0.25 release is not being produced?

Thanks!

**Comment by mrT23** [comment]
The official version appears here:
![image](https://github.com/user-attachments/assets/84a60414-6fe6-4c7c-8af4-2a8696490547)
and should be the reference to the docker.
work against that.

There was a pre-release of 0.24 in the past. This week was the official release, and now the docker version is locked
