### ISSUE TITLE
Use configuration.toml when running locally with docker?

### ISSUE THREAD

**Issue by dwirandyh** [Codium-ai/pr-agent#1225]
I have read the documentation about how to install & run locally with docker and it works well

```
docker run --rm -it -e OPENAI.KEY=<your key> -e CONFIG.GIT_PROVIDER=gitlab -e GITLAB.PERSONAL_ACCESS_TOKEN=<your token> codiumai/pr-agent:latest --pr_url <pr_url> review
```

 i want to know how to change configuration like changing model, etc use my own configuration.toml?

**Comment by mrT23** [comment]
In docker you don't change the configuration file.
You change parameters from it in a similar format to what you are already doing:

```
[CONFIG]
git_provider
```
->
` -e CONFIG.GIT_PROVIDER`
