### ISSUE TITLE
Preserve existing labels on Pull Requests

### ISSUE THREAD

**Issue by KalleV** [Codium-ai/pr-agent#123]
I noticed the PR Agent is removing existing labels assigned to the PR. For example, if a label is assigned by https://github.com/actions/labeler, it will get removed as soon as the task runs (i.e. /describe).

**Comment by mrT23** [comment]
you can control this behavior from the configuration file

```
[pr_description]
publish_description_as_comment=false
```

set 'publish_description_as_comment' to true, and the feedback will be given as a comment, not overwriting any existing data (header, label,...)

we can add a specific option for keeping only labels. However, i am not sure why we should keep only labels, but still change the header.

**Comment by okotek** [comment]
https://github.com/Codium-ai/pr-agent/pull/126

**Comment by KalleV** [comment]
> you can control this behavior from the configuration file
> 
> ```
> [pr_description]
> publish_description_as_comment=false
> ```
> 
> set 'publish_description_as_comment' to true, and the feedback will be given as a comment, not overwriting any existing data (header, label,...)
> 
> we can add a specific option for keeping only labels. However, i am not sure why we should keep only labels, but still change the header.

Makes sense. I noticed that option, but updating the original PR description is a very convenient feature. I find it easier to keep track of the PR content, especially with a lot of other automation steps posting various comments.

> #126

Thanks, that was fast! I tested the fix and it works great.
