### ISSUE TITLE
Option to dry run tool without submitting anything

### ISSUE THREAD

**Issue by user753** [Codium-ai/pr-agent#1237]
Hi
It would be useful if I could run any tool without submitting anything, 
something like `/review --dru-run=true` and it would print everything in terminal instead of github.

**Comment by user753** [comment]
> it is possible. review the documentation

I didn't find the answer. Could you tell me how to do it?

**Comment by mrT23** [comment]
This question suits the new `help` feature. use it.
https://github.com/Codium-ai/pr-agent?tab=readme-ov-file#september-21-2024

<img width="878" alt="image" src="https://github.com/user-attachments/assets/361f6b34-3aa1-4183-a03b-3b02afab9cfb">
