### ISSUE TITLE
[Feature Request] Option to Disable Auto-Trigger for Specific Pull Requests

### ISSUE THREAD

**Issue by woung717** [Codium-ai/pr-agent#1249]
My team often creates pull requests (PRs) from a combined branch that has already reviewed branches for production deployment. In these cases, executing auto-triggered tasks on such PRs is often unnecessary, as they may involve extensive code changes and place significant load on the pr-agent service. 
So, I suggest adding an option to selectively disable auto-triggered tasks on specific pull requests. This feature would allow teams to optimize their workflow and reduce unnecessary processing load. I have implemented and utilized this feature in our pr-agent codebase. 

For example, this can be implemented by adding a flag to the PR title or at the end of the PR description. When this flag is present, pr-agent will not automatically perform a review. However, if needed, users can still trigger a review manually by entering a command in a comment after the PR is created.

HyeonUng

**Comment by mrT23** [comment]
try asking first the new help tool
https://github.com/Codium-ai/pr-agent?tab=readme-ov-file#september-21-2024

```
/help
"add a flag to the PR title or at the end of the PR description. When this flag is present, pr-agent will not run automatically"
```

**Comment by woung717** [comment]
@mrT23 Oh, that seems like a good new tool. Thanks. In which PR would I have to ask using command?

**Comment by mrT23** [comment]
Whatever you want. Use an older one that was already closed, for example.

We will soon add it also for the [PR chat](https://chromewebstore.google.com/detail/pr-agent-chrome-extension/ephlnjeghhogofkifjloamocljapahnl), so the usage will be more natural

**Comment by woung717** [comment]
It seems that the ignore pr title configuration in the document page has not yet been updated. Or intentionally left out?
https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened

**Comment by mrT23** [comment]
what ?

https://github.com/Codium-ai/pr-agent/pull/1248#issuecomment-2368921748

**Comment by sam-717** [comment]
Oh, the ignore pr section has been moved to the additional configuration menu? It was in the Automation and Usage menu in the previous version, so I thought it had been removed. Thanks anyway.

**Comment by woung717** [comment]
Oh, the ignore pr section has been moved to the additional configuration menu? It was in the Automation and Usage menu in the previous version, so I thought it had been removed. Thanks anyway.

**Comment by mrT23** [comment]
use the help search, as i instructed
