### ISSUE TITLE
GitLab repo setting file gets applied to all subsequent merge requests

### ISSUE THREAD

**Issue by tgandrew** [Codium-ai/pr-agent#1265]
# Summary

I'm using the docker image `codiumai/pr-agent:0.24-gitlab_webhook`.

I've found that if a project has `.pr_agent.toml`, those settings get applied to the service and change the behavior for other projects.

# Steps to reproduce

1. Go to Project 1 (no .pr_agent.toml)
2. Create MR#1 in Project 1
3. pr-agent service now pick up the MR#1 and run the default pr_commands found at https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L237
4. Go to Project 2 (include .pr_agent.toml that sets `[gitlab] pr_commands = []`
5. Create MR#2 for Project 2
6. pr-agent service sees and applies the repo settings
7. pr-agent service does nothing for MR#2 because pr_commands is empty
8. Go back to Project 1 (still no .pr_agent.toml)
9. Create MR#3 in Project 1
10. pr-agent service sees MR#3 from Project1 but is still using Project2's applied settings, so pr-agent service ends up executing no pr_commands.

# Requested fix/change
 
If a project defines `.pr_agent.toml`, the project specific settings should be isolated to only that project. Other projects should use the default behavior.

**Comment by mrT23** [comment]
Are you referring to a **local** configuration file ?
https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options/

I don't understand how a local configuration file of one project can impact another one. See
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/git_providers/gitlab_provider.py#L464
```
    def get_repo_settings(self):
        try:
            contents = self.gl.projects.get(self.id_project).files.get(file_path='.pr_agent.toml', ref=self.mr.target_branch).decode()
            return contents
        except Exception:
            return ""
```

since I have not received this feedback from other gitlab users, I think it is related to some local issue of yours.
Try to run from CLI. catch a breackpoint in the line I sent, and review the content.

**Comment by tgandrew** [comment]
Sure, I'll get some more info via debugging.

**Comment by tgandrew** [comment]
After running through the debugger,  found that `context["settings"]` is never being set, because I'm using a `GITLAB.SHARED_SECRET` on a private instance of gitlab (not gitlab.com).

When  `context["settings"]` is not being set, `get_settings()` is returning the `global_settings` which then are being modified by `apply_repo_settings` at https://github.com/Codium-ai/pr-agent/blob/v0.24/pr_agent/git_providers/utils.py#L40.

If I simply move https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/servers/gitlab_webhook.py#L157 `context["settings"] = copy.deepcopy(global_settings)` up to the start of `inner` function before any of the if statements are hit, then it fixes the bug.

**Comment by mrT23** [comment]
On your local deployment, you can change the code to suit your needs.

However, the issue has been addressed (in a safer way) in PR-Agent-Pro, and this is the platform we recommend for working with highly commercial environments like private instances of GitLab
https://qodo-merge-docs.qodo.ai/overview/pr_agent_pro/#overview

**Comment by mrT23** [comment]
fixed here:
https://github.com/Codium-ai/pr-agent/commit/cd158f24f68525a45c66f0519d8f7306361ce12b

**Comment by tgandrew** [comment]
Thank you for the help @mrT23 !
