### ISSUE TITLE
Support new openAI models (o1-mini/o1-preview)

### ISSUE THREAD

**Issue by fnava621** [Codium-ai/pr-agent#1278]
Getting the following error

{"text": "Error during LLM inference: litellm.BadRequestError: OpenAIException - Unsupported value: 'messages[0].role' does not support 'system' with this model.\n", "record": {"elapsed": {"repr": "0:00:05.698555", "seconds": 5.698555}, "exception": null, "extra": {}, "file": {"name": "litellm_ai_handler.py", "path": "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py"}, "function": "chat_completion", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 218, "message": "Error during LLM inference: litellm.BadRequestError: OpenAIException - Unsupported value: 'messages[0].role' does not support 'system' with this model.", "module": "litellm_ai_handler", "name": "pr_agent.algo.ai_handlers.litellm_ai_handler", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140078980955008, "name": "MainThread"}, "time": {"repr": "2024-10-08 21:15:43.576495+00:00", "timestamp": 1728422143.576495}}}

**Comment by fnava621** [comment]
So fast! Thank you! 👍

**Comment by fnava621** [comment]
Can I request a rebuild of the docker Github action image? (Please ignore if it happens nightly and it hasn't run)

**Comment by mrT23** [comment]
there is a new docker
