### ISSUE TITLE
Unable to run Codium workflow

### ISSUE THREAD

**Issue by SprintMobile** [Codium-ai/pr-agent#1287]
Hello guys, just found this amazing GHA action and I tried to use it, but I am getting this error:

`{"text": "Error during LLM inference: litellm.NotFoundError: OpenAIException - The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.\n", "record": {"elapsed": {"repr": "0:00:41.057211", "seconds": 41.057211}, "exception": null, "extra": {}, "file": {"name": "litellm_ai_handler.py", "path": "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py"}, "function": "chat_completion", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 234, "message": "Error during LLM inference: litellm.NotFoundError: OpenAIException - The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.", "module": "litellm_ai_handler", "name": "pr_agent.algo.ai_handlers.litellm_ai_handler", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 139653849336704, "name": "MainThread"}, "time": {"repr": "2024-10-11 13:59:58.714431+00:00", "timestamp": 1728655198.714431}}}`

This is my workflow yml file:
`name: AI Code Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

I have created an Open AI API Key, I also have created a GitHub token, so I am not sure what I an missing.
I also tried adding the model like this but still didn't work. 
CONFIG.MODEL: "gpt-3.5-turbo"

Any suggestion? What am I doing wrong?

**Comment by mrT23** [comment]
We cannot debug your personal deployment.
you can always try pr-agent pro, where installation is even easier: https://qodo-merge-docs.qodo.ai/overview/pr_agent_pro/

**Comment by SprintMobile** [comment]
Hi @mrT23.

Thank you for your response. With all due respect, simply suggesting to "install the pro version" isn't a sufficient solution for some of us. Many users, myself included, would like to try the free version first to evaluate the product before considering an upgrade.

To clarify, there’s nothing related to my personal or local environment causing the issue. Everything is set up entirely on GitHub. I followed the steps outlined in the installation manual using GitHub Actions: the YAML file is correctly in place, and I’ve added the necessary OpenAI API key. The agent starts as expected on commits, but it returns the error mentioned above.

The core issue is that I haven’t been able to find any documentation explaining what this specific error means or how to resolve it. Could you please provide some guidance or clarification on this?

Thanks in advance for your help!

**Comment by mrT23** [comment]
we cannot debug your personal deployment.

You clearly have a personal bug with your keys\access, as the error clearly say:

`The modelgpt-4o-2024-05-13 does not exist or you do not have access to it`

Catch a breakpoint, and try to see what wen wrong.

**Comment by SprintMobile** [comment]
Could you clarify what you mean by "caching a breakpoint"? Where or how should I implement that?

As a developer, I followed the setup steps by adding the YAML file, creating an OpenAI API key, but I’m encountering an error every time I run Codium's product action.

The setup seems pretty straightforward, so I’m unsure what could be wrong. This is all that’s mentioned in the setup guide. Additionally, the model (gpt-4o-2024-05-13) seems to be the fallback from your configuration files:
(https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml)).

I even tried using a custom model, as mentioned in my initial message, but it didn’t work either.

Is there anyone else who has experienced this error or a similar issue?

**Comment by CristinaSolana** [comment]
I had a similar error and I changed the models, here's what I've got set in the pr_agent.toml config atm that is working:

```
[config]
model="gpt-4o-mini"
model_turbo="gpt-3.5-turbo"
fallback_models=["gpt-4o-mini-2024-07-18"]​
```

**Comment by mrT23** [comment]
@CristinaSolana 
The documentation clearly instructs to do this:
https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#changing-a-model

So indeed this is the way.

**Comment by CristinaSolana** [comment]
> @CristinaSolana The documentation clearly instructs to do this: https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#changing-a-model
> 
> So indeed this is the way.

Yes, I think what might happen is that people copy pasta this [config](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml) and those models don't always seem to work. Not sure of the reason, but the error makes it obvious what's happening so I quickly went and looked at what models I could replace them with and all good. 👍
