### ISSUE TITLE
Agent features

### ISSUE THREAD

**Issue by marcelosousa** [Codium-ai/pr-agent#129]
Hi ✋ ,

From what I can understand, currently the project is a wrapper on calls to a LLM. An agent would connect with other tools directly; is there a roadmap on those features?

**Comment by mrT23** [comment]
See https://github.com/Codium-ai/pr-agent/blob/main/README.md#roadmap for roadmap

We are open to suggestions\PRs regarding other non-LLM tools. 

However, and do what we see in other "agent-like" projects, we will prioritize tools that truly give value to the user. We are not chasing additional tools, without value to the user, just to claim "we are AGI"

**Comment by mrT23** [comment]
I am closing this, as it is more a "discussion" than an issue.

Welcome to open relevant PRs for "agents", or a discussion in the "Discussion" section
