### ISSUE TITLE
[questions] : LLM structured output: YAML vs. JSON comparison

### ISSUE THREAD

**Issue by mofanke** [Codium-ai/pr-agent#1296]
## OpenAI's Approach

OpenAI, as documented in their [Structured Output Guide](https://platform.openai.com/docs/guides/structured-outputs/introduction), uses JSON for structured outputs. 

## PR Agent's Approach

PR Agent, on the other hand, implements YAML for structured outputs. 

What advantages does YAML have compared to JSON?

**Comment by mrT23** [comment]
We discuss this issue thoroughly here:
https://arxiv.org/pdf/2401.08500

![image](https://github.com/user-attachments/assets/47207070-9d55-43f3-80e8-09eba2a5ce07)
