### ISSUE TITLE
Ignore "Preparing answer..." comments - prefer 👀 emoji

### ISSUE THREAD

**Issue by marcelosousa** [Codium-ai/pr-agent#130]
The "Preparing answer..." comment can be quite noisy and spammy. Is there a way to turn it off? 

IMO, the best experience is to put the 👀 emoji on the comment.

**Comment by mrT23** [comment]
in the configuration file:
[config]
**publish_output_progress=true**

set it to _false_

**Comment by okotek** [comment]
This can be done in repo level by adding these lines to .pr_agent.toml. 
We still would like to implement the eyes emoji on the calling comment.. @idavidov maybe you can help?

**Comment by idavidov** [comment]
@okotek yes, let me take a look on it

**Comment by okotek** [comment]
#182 added this functionality by default on GitHub. Still need to implement on Gitlab

**Comment by GadiZimerman** [comment]
@never-known-soldier FYI

**Comment by tjwp** [comment]
In my deployment, I've also added the 👀 on the PR description with the GitHub app if automatically handling a command for the pull request. I can contribute that back if there's interest.

**Comment by never-known-soldier** [comment]
@tjwp could you please raise new pr request.
