### ISSUE TITLE
URLs Generated for GitLab Result in 404 Errors

### ISSUE THREAD

**Issue by owayo** [Codium-ai/pr-agent#1314]
In the `git_providers/gitlab_provider.py` file, the URLs generated for GitLab are causing 404 errors.
The issue lies in the use of source_branch in the `get_line_link` and `generate_link_to_relevant_line_number` methods.
These URLs should reference the exact commit ID (head_sha) instead of the branch name (source_branch).
Additionally, the inclusion of `?ref_type=heads` in the URL is also contributing to the 404 errors.

I propose the following changes to address this issue:

 * Replace source_branch with head_sha in the URL generation.
 * Remove ?ref_type=heads from the generated URLs.
 * 
The following sed commands can be used as a reference to implement these changes:
```
$ sed -i 's@/-/blob/{self\.mr\.source_branch}/@/-/blob/{self\.mr\.diff_refs\['\''head_sha'\''\]}/@g' /app/pr_agent/git_providers/gitlab_provider.py
$ sed -i 's/\?ref_type=heads//g' /app/pr_agent/git_providers/gitlab_provider.py
```

With these modifications, the URLs will reference the correct commit SHA and the unnecessary `?ref_type=heads` will be removed, preventing 404 errors from occurring.

The environment is as follows:
 * GitLab CE (self-hosted): 17.5.1

**Comment by mrT23** [comment]
Hi @owayo 

i cannot reproduce the errors on my self-host gitlab deployment

For example, I have a link:

https://gitlab.codium-inc.com/gitlab-instance-0a176887/pr-agent/-/blob/ok/azure_openai_doc_fix1/requirements.txt?ref_type=heads#L26-L26

That works fine.

Does this problem happens to you always ? on specific PRs with something unique in them ?
I have not heard of problems with our gitlab self-hosted links from other users.

![image](https://github.com/user-attachments/assets/72603051-4b10-49fe-a417-bf977d2e09cb)
![image](https://github.com/user-attachments/assets/ab2016b3-cb7f-4219-86c8-c6ed843b76bb)
![image](https://github.com/user-attachments/assets/e53e059a-5f3e-4066-8d2e-abd38645c7df)

**Comment by owayo** [comment]
Yes, the 404 error always occurs.

If this is a problem specific to my environment, I will replace the URLs using the sed command as suggested.

Thank you very much.
