### ISSUE TITLE
Some configurations don't seem to work

### ISSUE THREAD

**Issue by draialexis** [Codium-ai/pr-agent#1329]
## Thanks

I've been giving this tool a whirl recently, and enjoying it. Thank you for putting it out there.

## My config issues

I'm using GitLab, but I'm not sure whether that matters for all those settings. I will rank them in order of importance to me (and -- if this all gets cleared up -- to my team, probably), starting with the least important ones. 

The settings I'm using are in `.pr-agent.toml` at the root of my repo. They are :

<details>
<summary><h3>Description help comment</h3></summary>

`[pr_description]` > `enable_help_comment`

I tried setting it to:

```toml
enable_help_comment = false
```

But the descriptions created still do feature '💡 PR-Agent usage: Comment /help "your question" on any pull request to receive relevant information'
</details>
<hr>

<details>
<summary><h3>Suggestion self review</h3></summary>

`[pr_code_suggestions]` > `demand_code_suggestions_self_review`
`[pr_code_suggestions]` > `fold_suggestions_on_self_review`
`[pr_code_suggestions]` > `code_suggestions_self_review_text`

I saw [this example](https://qodo-merge-docs.qodo.ai/tools/improve/?h=demand_code_suggestions_self_review#self-review) and tried setting those to:

```toml
demand_code_suggestions_self_review = true
fold_suggestions_on_self_review = true
code_suggestions_self_review_text = "**Author self-review**: I have reviewed the code suggestions, and addressed the relevant ones."
```

But I still didn't see a checkbox for author self-review, in the code suggestions I got.
</details>
<hr>

<details>
<summary><h3>Commitable code suggestions</h3></summary>

`[pr_code_suggestions]` > `commitable_code_suggestions`

I saw [this example](https://qodo-merge-docs.qodo.ai/tools/improve/?h=commitable_code_suggestions#example-usage) and tried setting it to:

```toml
commitable_code_suggestions = true
```

But the code suggestions I got were still in an html table in a single comment, and not commitable. 
</details>
<hr>

<details>
<summary><h3>Ignore logic</h3></summary>

`[config]` > `ignore_pr_title`

I tried setting it to:

```toml
ignore_pr_title = ["^Draft:"]
```

But when I then created a MR with its title starting with `Draft:...`, PR agent's pipeline does get triggered and I get a description, review, and improvement suggestions. I did check that the regex I used matches my MR title.

Same problem with

`[config]` > `ignore_pr_labels`

I tried setting it to:

```toml
ignore_pr_labels = ["auto-generated", "no-pr-agent"]
```

But when I created MRs with those labels, I still got a description, review and suggestions.

> 💡 I can set up my own ignore logic within my GitLab CI file
</details>
<hr>

<details>
<summary><h3>Models</h3></summary>

`[config]` > `model`
`[config]` > `model_turbo`
`[config]` > `fallback_models` 

I tried setting them all to gpt-4o-mini like so:

```toml
model = "gpt-4o-mini"
model_turbo = "gpt-4o-mini"
fallback_models = ["gpt-4o-mini"]
```

But I'm still seeing requests made to other (pricier) models

![image](https://github.com/user-attachments/assets/3e9d289e-401c-4e21-a4ef-30980220f4ff)

_I have no workaround for this one, and it's a major issue for me_
</details>

**Comment by mrT23** [comment]
we cannot debug your personal configuration. it seems your setup is wrong somehow. only you can find the problem and solve it. Its definitely not a pr-agent problem.
 
 Thoroughly review the documentation and try to see the issue: https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options/
 Also review your logs. 
 
 you can always do online commenting to make sure the configuration indeed work
 
` /improve --pr_code_suggestions.commitable_code_suggestions=true`

**Comment by draialexis** [comment]
Thanks for the rapid response.

It brings me no joy to admit that I had misnamed my config file as ".pr-agent.toml" with a - instead of a _

After testing each point, I’m happy to report that basically everything works as documented.

The only remaining issue is that my "ignore" logic isn’t working in GitLab CI (the agent still sends requests even if the MR title or label should trigger a skip), but I’ve found a useful workaround

**Comment by mrT23** [comment]
The ignore logic is indeed supported currently only in the app, not on action
