### ISSUE TITLE
Change to local model error

### ISSUE THREAD

**Issue by hgcdanniel** [Codium-ai/pr-agent#1339]
Thanks for sharing this wonderful project!
when I want to use local model  as shown in https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#changing-a-model
which I do is as follows:
pr_agent/settings/configuration.toml
model="/storage/ai_data/codeLLMs/CodeLlama-34b-Instruct-hf"
model_turbo="/storage/ai_data/codeLLMs/CodeLlama-34b-Instruct-hf"
fallback_models=["/storage/ai_data/codeLLMs/CodeLlama-34b-Instruct-hf"]
but still has  error:
Error generating PR description hgcdanniel/binary_llm/1: Failed to generate prediction with any model of ['/storage/ai_data/codeLLMs/CodeLlama-34b-Instruct-hf', '/storage/ai_data/codeLLMs/CodeLlama-34b-Instruct-hf']
so what I should do ?

**Comment by mrT23** [comment]
You are not deploying your models correctly.
Just giving an address on your storage is wrong.

Review the internet on how to deploy models (ollama for example)
