### ISSUE TITLE
[Feature Request]  Include References in Review Comments

### ISSUE THREAD

**Issue by Takumi-Hanawa** [Codium-ai/pr-agent#1352]
Hi,

I’d like to request a new feature:
Could you include references or sources that support the review comments provided by PR-Agent? This would help developers better understand the rationale behind each suggestion and improve the learning process.

For example, links to relevant documentation, style guides, or coding best practices would be incredibly helpful.

**Comment by mrT23** [comment]
Hi.
Some thoughts and observations about the topic of  `links to relevant documentation, style guides, or coding best practices`:

1) LLM cannot, in principle, reliably give direct reference links. They fail to do that when asked (welcome to try), and even if succeded, probably the additional guardrails will block that (they don't want you to know what they were trained on)

2) while not direct links, we do add a 'why' section for _each_ suggestion we give, with thorough reasoning

![image](https://github.com/user-attachments/assets/e71c8132-340a-4372-b720-2ddc4caedb57)

3) Some pro features, like the 'similar code' tool, are aimed directly at that:
https://qodo-merge-docs.qodo.ai/tools/similar_code/

4) another pro feature relating to this is reading the organization 'best_practice' file:
https://qodo-merge-docs.qodo.ai/tools/improve/#best-practices
this enables to give more tailored suggestions, based on specific needs of the organizations, and also the improve the reasoning behind the suggestions
