### ISSUE TITLE
Ollma Local integration not working and need help to integrate with bitbucket.org with personal token

### ISSUE THREAD

**Issue by akashsenta13** [Codium-ai/pr-agent#1361]
Hello There,

I am running Ollma locally on my Machine in CLI and I have API endpoint running as per below
```
[ollama]
api_base = "http://127.0.0.1:11434/" 
```
Also, I have done settings for models as this 
```
[config]
# models
model="ollama/llama3.2"
model_turbo="ollama/llama3.2"
fallback_models=["ollama/llama3.2"]
```

When I am trying to run PR Review with this configuration I am not able to run successfully. Getting errors as below 

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/5185697c-991c-440f-bfa1-5aaf62b0c66d">

------

Also
I need help regarding getting Bitbucket (using bitbucket.org) bearer_token for reviewing PR from multiple Repo, i can create single Repo token but i need to use as Generic token for all Repo in account.

**Comment by mrT23** [comment]
We cannot debug your personal deployment.
something is wrong there.

triple and quadruple check that you have deployed a valid model, and you are able to access it.
