### ISSUE TITLE
Help me understand the max_context_tokens setting

### ISSUE THREAD

**Issue by buddhamangler-cbre** [Codium-ai/pr-agent#1368]
I notice for pr_code_suggestions the default max_context_tokens is 14000.  I tried to sort through the code and see the effect and it seems to just reduce the max tokens setting.  I'm curious why?  Especially for models that can handle say 128k tokens, what purpose does this serve?

[pr_code_suggestions] # /improve #
max_context_tokens=14000

**Comment by mrT23** [comment]
To increase quality.
With very long context, the quality of LLMs drops significantly.

If the context is 30,000 tokens (for example), we will do 3 smaller calls instead of one big call, and get better suggestions.

But it's configurable.
If you want to save calls, set it to 100K, its perfectly ok.

**Comment by buddhamangler-cbre** [comment]
That's interesting and makes sense, but does this play nice with extended? Correct me If I'm wrong, but pr_code_suggestions only appears to make multiple calls if extended is enabled....via _prepare_prediction_extended.  If extended was disabled, wouldn't this default setting force the token count to 14000?

https://github.com/Codium-ai/pr-agent/blob/d4d9a7f8b456f57422fae1e819c98f6f40966402/pr_agent/tools/pr_code_suggestions.py#L100-L103

**Comment by buddhamangler-cbre** [comment]
That's interesting and makes sense, but I'm having a hard time understanding how this interacts with extended? Correct me If I'm wrong, but pr_code_suggestions only appears to make multiple calls if extended is enabled....via _prepare_prediction_extended.  If extended was disabled, wouldn't this default setting force the token count to 14000 unnecessarily?

https://github.com/Codium-ai/pr-agent/blob/d4d9a7f8b456f57422fae1e819c98f6f40966402/pr_agent/tools/pr_code_suggestions.py#L100-L103

**Comment by mrT23** [comment]
the default is on.

all the best

**Comment by buddhamangler-cbre** [comment]
Appreciate the response, but yes I am aware the default is on, however the behavior when it is off is potentially confusing as the max_content_tokens is respected regardless of the extended default.  

In your opinion, would it might make better sense to only respect the max_context_tokens setting if extended were true?  After all, you said yourself when asked before that the purpose of that setting is specifically in the case where the pr is split into multiple calls, but the code is using it regardless if you want to split or not.

**Comment by buddhamangler-cbre** [comment]
perhaps rename to max_context_tokens_extended? and only respect it when extended is true?

**Comment by buddhamangler-cbre** [comment]
something like this....(with optional rename if you wanted)

`
        # extended mode
        try:
            self.is_extended = self._get_is_extended(args or [])
        except:
            self.is_extended = False

        if self.is_extended:
            # limit context specifically for the improve command, which has hard input to parse:
            if get_settings().pr_code_suggestions.max_context_tokens:
                MAX_CONTEXT_TOKENS_IMPROVE = get_settings().pr_code_suggestions.max_context_tokens
                if get_settings().config.max_model_tokens > MAX_CONTEXT_TOKENS_IMPROVE:
                    get_logger().info(f"Setting max_model_tokens to {MAX_CONTEXT_TOKENS_IMPROVE} for PR improve")
                    get_settings().config.max_model_tokens_original = get_settings().config.max_model_tokens
                    get_settings().config.max_model_tokens = MAX_CONTEXT_TOKENS_IMPROVE            
            num_code_suggestions = get_settings().pr_code_suggestions.num_code_suggestions_per_chunk
        else:
            num_code_suggestions = get_settings().pr_code_suggestions.num_code_suggestions
`

**Comment by buddhamangler-cbre** [comment]
I suppose I can see your point now that I think about it, the quality of improve is bad unless the tokens are limited...period.  So extended or not, to increase quality the limit is set low.  Thanks for the responses.  Great work BTW
