### ISSUE TITLE
In-line PR comments sometimes request redundant changes

### ISSUE THREAD

**Issue by KalleV** [Codium-ai/pr-agent#137]
I’m fairly often seeing this type of PR feedback where the change already being applied is added as the PR feedback comment:
![image](https://github.com/Codium-ai/pr-agent/assets/5942028/f76eebb4-33fc-40f5-bc5e-3f8b0ab44d1f)

Another seemingly consistent way to reproduce this seems to be when adding try / catch around a code block that did not have it before.

**Comment by okotek** [comment]
Do you have a public PR you can share with this behavior?

**Comment by KalleV** [comment]
I can try to set up a reproduction of this issue but I can see the prompts are clearly trying to avoid this already:
https://github.com/Codium-ai/pr-agent/blob/36ab12c486f96db54185b09e49015001c7c1068b/pr_agent/settings/pr_reviewer_prompts.toml#L8

Do you think tweaking that instruction or its placement would make a difference? Something like:
```
- It is essential to avoid suggesting changes that mirror modifications already introduced in the new PR code (the '+' lines). Ensure that your feedback brings new insights and does not reiterate the changes already incorporated in the PR.
```

**Comment by okotek** [comment]
Cc @mrT23

**Comment by KalleV** [comment]
I wasn't able to create a minimum public reproduction yet but I came across a PR consistently requesting a try/catch. Not sure if the PR size makes a big difference but according to https://llmtokencounter.com/, the system prompt + user prompt is about `4801 tokens 19205 characters 5004 words`.

I couldn't consistently prove small tweaks such as:
```diff
+ - It is essential to avoid suggesting changes that mirror modifications already introduced in the new PR code (the '+' lines).
- - Make sure not to provide suggestions repeating modifications already implemented in the new PR code (the '+' lines).
```
Or rearranging the system instructions led to a consistently better response but it was fun to try!

**Comment by mrT23** [comment]
ok.

notice that the '/improve' tool works differently in terms of patch and prompt design, and I think it will happen less there

**Comment by mrT23** [comment]
I am closing this issue. if you encounter this again in the '/improve' command, feel free to open another

**Comment by KalleV** [comment]
Sounds good, thank you!
