### ISSUE TITLE
[Feature Request] Version Information

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1370]
* Add way to programically obtain metadata from pip/pyproject.toml.
* Add version metadata to langchain context
* Add a version command
* Optionally add version metadata to pr agent accepted suggestions

**Comment by mrT23** [comment]
Qodo Merge Pro provides dramatically better logging abilities.
It includes dashboards, accepted suggestions tracking, and more.

https://qodo-merge-docs.qodo.ai/overview/pr_agent_pro/
https://qodo-merge-docs.qodo.ai/core-abilities/fetching_ticket_context/#jira-integration
https://qodo-merge-docs.qodo.ai/core-abilities/impact_evaluation/
https://qodo-merge-docs.qodo.ai/core-abilities/impact_evaluation/#dashboard-metrics

If you find these abilities needed, consider purchasing Qodo Merge Pro.

We will not prioritize them in the open source version
