### ISSUE TITLE
add support for AWS codecommit

### ISSUE THREAD

**Issue by aiseei** [Codium-ai/pr-agent#138]
Would be great to have an option for some of us. 
Great tool!

**Comment by pzarfos** [comment]
I'm going to take a stab at implementing CodeCommit

**Comment by pzarfos** [comment]
I have the "review" feature working from the CLI for CodeCommit, on a simple PR at least.

I am going to work on getting it working on a PR with additions/deletions, and improve the exception handling.
Time permitting, I hope to have an initial PR ready for review next week for CodeCommit.
