### ISSUE TITLE
[Documentation Proposal] Local configuration using environment variables

### ISSUE THREAD

**Issue by addianto** [Codium-ai/pr-agent#1398]
Good day.

I was trying to self-host Qodo Merge on a server using Docker.
Initially, I had difficulty figuring out how to configure the container using environment variables.
The [official documentation](https://qodo-merge-docs.qodo.ai/installation/locally/#using-docker-image) for running the project as a Docker container was not much help.
Only after looking at similar issues, e.g. #819 and #1225, did I understand that the configuration is managed using [Dynaconf](https://www.dynaconf.com/).

To help others who might want to run Qodo Merge as a container, I think the documentation section about running Qodo Merge as a container can be improved by, at least, providing examples of how to override the local configuration file using environment variables.
I could help contribute a PR for this.

**Comment by mrT23** [comment]
Documentation contribution is always welcomed 👍
