### ISSUE TITLE
Support for ChatGPT-o1

### ISSUE THREAD

**Issue by BillChirico** [Codium-ai/pr-agent#1399]
When can we expect support for ChatGPT 4o1?

**Comment by mrT23** [comment]
we support the preview model, you can open a PR to add also the latest one
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/__init__.py#L25

But actually, it is supported currently, just use a custom model tokens:
https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#custom-models

**Comment by BillChirico** [comment]
> we support the preview model, you can open a PR to add also the latest one
> 
> https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/__init__.py#L25
> 
> 
> 
> But actually, it is supported currently, just use a custom model tokens:
> 
> https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#custom-models

Would it just be "o1" in this case? I'll open a PR for it

**Comment by mrT23** [comment]
i actually think there isnt such model yet

https://docs.litellm.ai/docs/providers/openai
<img width="751" alt="image" src="https://github.com/user-attachments/assets/f0663f8b-c138-4e3a-b68d-c249202da1d0" />


so use 'o1-preview' which we already support
