### ISSUE TITLE
`publish_output_no_suggestions: false` is ignored 

### ISSUE THREAD

**Issue by TimPetricola** [Codium-ai/pr-agent#1404]
In https://github.com/Codium-ai/pr-agent/pull/1331, a new `publish_output_no_suggestions` option was added to avoid posting a comment when there is no suggestion.

However, the code using this config has been removed in https://github.com/Codium-ai/pr-agent/commit/d34edb83ff3d73b4bee1f6f3fb14f7b23589ed1a#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117bL123, I'm guessing by mistake.

Would it be possible to re-introduce the feature?

Thanks a lot :)

**Comment by mrT23** [comment]
thanks, i think https://github.com/Codium-ai/pr-agent/pull/1407 will fix this
