### ISSUE TITLE
[Feature Request] - Ability to configure GitHub App

### ISSUE THREAD

**Issue by esauser** [Codium-ai/pr-agent#155]
I've seen mentions to tweak configuration for various things, but that is not currently possible when using the GitHub App.

**Comment by mrT23** [comment]
I think this issue was resolved. any configuration value can now be edited online, see example in:
https://github.com/Codium-ai/pr-agent/pull/159
(we asked and got only on code suggestion)
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/e0e639fa-b5fa-4ef5-bd4f-4f1434db3d18)

**Comment by esauser** [comment]
I was more thinking of persisted configuration.  For example, in a file committed to the repo.

**Comment by zmeir** [comment]
Hi @mrT23,

I tested this feature on a custom deployment of the PR-Agent app (not in a GitHub app) and while this feature works, it has the side-effect of altering the configuration state globally (the `settings` object in `pr_agent/config_loader.py`) for all subsequent requests.  
Do you have any plans to support such deployments, and fixing this override feature to only override the configuration per-request?

**Comment by okotek** [comment]
This PR https://github.com/Codium-ai/pr-agent/pull/164 reads the <REPO_ROOT>/.pr_agent.toml settings and merges them
