### ISSUE TITLE
[Feature Request] - Automate /describe and /improve for GitHub App

### ISSUE THREAD

**Issue by esauser** [Codium-ai/pr-agent#156]
The GitHub App automatically runs /review when a PR is opened, but /describe -c and /improve are not automated.  We'd like these to also run, or maybe a single command that does all three?

**Comment by ilyadav** [comment]
Hi @okotek i can work on this and #157, make it configurable for those who wish make any of this automatically 
I am thinking about put it in settings/configuration.toml

[pr_reviewer]
automatic_describe=false
automatic_review=false
automatic_improve =false

and then use it in pr_processing.py
if you want me to help here I'll be happy to take it

Best regards
Ilya

**Comment by okotek** [comment]
The difficulty here is that the same GitHub app needs to be configured differently for different installations, and they all share the same configuration files. We could do:
- Some persistence of settings per installation, need to be defined and decide how to manipulate. (/config command? Dedicated endpoint?)
- A user might commit a specially named file into their repository (.pr_agent) with settings that will override the default. 
- A command embedded in the PR title :( 
Any other ideas?

**Comment by esauser** [comment]
I highly recommend a file committed to the repository.

**Comment by idavidov** [comment]
so we will go with special file, i'll start work on it and update

**Comment by idavidov** [comment]
hi 

it took little bit more time to get into it that i planned and i've started today.

when i build my test environment i recognized as as per current readme for setup github app we not require setup permission to read repo so we can see only files with included in PR not special file which probably will be setup once and not change too match
in github app this approach won't work, unless i missed something

setting per installation probably also not good idea for big project devops team will setup it once and developers won't be able to change it later, for small setups when devs do everything alone it better idea

command or keyword embedded in PR ugly but works for any cases.

also original esauser idea for new command for all 3 maybe nice path, but unless we want put this new command as default instead /review i don't see how it can help 

bottom line i only see command or keyword embedded in PR can be possible solution, but would like to see what do you guys think


Best regards
Ilya

**Comment by esauser** [comment]
@idavidov have you seen the work done here? At a minimum, it seems like there ought to be a way to have a single command they always runs and then determines what to do based on the config. Unless maybe this doesn't actually work as described? https://github.com/Codium-ai/pr-agent/issues/155

**Comment by tjwp** [comment]
I implemented an `automatic_review` setting in our fork because I wanted to install the app for all repos, but allow individual repos to opt into reviews. I can open a PR with the changes if that would be helpful.

**Comment by idavidov** [comment]
Sorry, I had unexpected changes in my startup and wasn't active here last week+
is this still open, or would we love to go with @tjwp  PR?

**Comment by DesignMike** [comment]
Is it possible to do this (automated /review --extended) with Github Actions?

**Comment by mrT23** [comment]
yes
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-action
