### ISSUE TITLE
[Feature Request] Include /review -i in GitHub App automation

### ISSUE THREAD

**Issue by esauser** [Codium-ai/pr-agent#157]
The GitHub App automatically runs /review when a PR is opened, but it does not do anything to subsequent pushes to the PR.  We'd like to run /review -i for each subsequent push.

**Comment by bperreault** [comment]
I would like to add perhaps it could be an option. I prefer to re-request review personally.

**Comment by idavidov** [comment]
i believe #215 is right for this purpose correct @tjwp ?

**Comment by tjwp** [comment]
This would need some additional changes to handle incremental. It would need to look for a `synchronize` action on a PR and trigger an incremental review (only available by arg currently). It should probably be an additional setting.

**Comment by mrT23** [comment]
i am not sure you would like review to be run automatically every new commit. it can flood the git with a lot(!) of messages.

my suggestion - use it manually, when needed.

**Comment by esauser** [comment]
This can almost be accomplished already.  `synchronize` can be added to the [handle_pr_actions[(https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L79) and `improve -i` can be added to [pr-commands](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L80-L83).  The only thing missing is being able to do it differently the first time vs. every time.

If the config was separated out to allow you to specify specific commands for specific actions we'd have that flexibility.  Maybe something to consider @mrT23 .

**Comment by mrT23** [comment]
Technically its possible, i agree.

However, optional features still need to be viable.
In practice, even as an option, would you really want 10-20 review feedback messages in a single PR ?
we tried this way (Triggering on every commit) when starting developing pr-agent, and it was awful 

I think a better option is to enable to update the initial review message after every commit, so review feedback will always be up-to-date.

but I am not sure. open for feedback

**Comment by esauser** [comment]
@mrT23 I would expect it to update existing, yes.
