### ISSUE TITLE
[Feature Request] Skip large diffs on GitLab

### ISSUE THREAD

**Issue by vavido** [Codium-ai/pr-agent#161]
When huge files (i.e. autogenerated code etc.) are part of a GitLab repo, by default it shows the following message:

![image](https://github.com/Codium-ai/pr-agent/assets/7227663/7b241968-01df-4459-a0af-f8603fbe8af0)

When trying to review such a PR using the review bot, it produces the following warning:
```
WARNING:root:File was modified, but no patch was found. Manually creating patch: funnelui/graphql.schema.json.
```
and then takes around 8 minutes (running in a Docker container on an M1 Mac) to build the diff.

Since files with thousands of lines are likely to be auto-generated code anyway, it would be nice to either
- have an option to ignore diffs that are hidden by default in GitLab (though I'm unsure if there is proper support for this in the GitLab API)
- have an option to pass an ignore list of files to always ignore to the agent

I'm not sure how GitHub handles files with a huge diff, but a similar feature might be useful for GitHub as well.

**Comment by mrT23** [comment]
Hi @vavido 

Let's start with GitHub current policy:

In GitHub we addressed this issue (maybe not optimally) like this:
large files patch comes empty by default. We specifically bring the original files, and compare them to generate the patch
https://github.com/Codium-ai/pr-agent/blob/6605f9c444c1e5697378610a0be084317a9198a9/pr_agent/algo/utils.py#L185
https://github.com/Codium-ai/pr-agent/blob/6605f9c444c1e5697378610a0be084317a9198a9/pr_agent/git_providers/github_provider.py#L100

To avoid waiting for very large files, we will need to avoid bringing the original files to begin with.
`diff_files = list(git_provider.get_diff_files())`


regarding Gitlab, I need to check. do you have an example for public repo with such a large commit ?

**Comment by pushpanktugnawat** [comment]
@vavido Can you help me or give me a guide on how you enabled `pr-agent` over `GitLab`? I follow the installation guide but always complain about some weird errors.

**Comment by mrT23** [comment]
Hi @vavido 
i took an extra look at GitHub API.
i don't see a mechanism there to look at file size before actually bringing them

However, we have a bit more complicated solution for your specific issue:
1. set config.use_extra_bad_extensions = true
2. in `pr_agent/settings/language_extensions.toml` add 'json' to to 'extra list
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/ef590c26-3305-46b4-8007-feb4648cc740)

I think it's a reasonable solution for quite a unique problem.
