### ISSUE TITLE
[Feature Requests] Do not limit suggestions

### ISSUE THREAD

**Issue by esauser** [Codium-ai/pr-agent#165]
Current configuration allows for a number of suggestions.  Can we get all of them?

**Comment by mrT23** [comment]
There is no such thing as "all suggestions"

- Ask GPT-4 for 100 suggestions, you might get 100 suggestions. But  most of them will probably be bad\repetative\simplistic

- In addition, there is a limit on the number of output tokens, so even without a cap, you won't get "all suggestions". 

- Limiting the number of output suggestions is the right way to go, as we try to encourage the model to focus on the most important ones. We can still use a relatively high cap (~7-8)

I recommend reviewing the [prompt](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/pr_code_suggestions_prompts.toml). Try to remove lines 8 and 24, and you will see you still don't get "all suggestions", as there is no such thing.

**Comment by esauser** [comment]
How about all the most important ones?  Setting an arbitrary limit doesn't make sense either.  The two options seem to be ditch to ditch. How do we find the happy medium?

**Comment by mrT23** [comment]
the prompt says " up to {{ num_code_suggestions }} ". It can provide less

More generally, It's always a challenge to prompt LLM, especially when the input is large and complicated like we have in PRs code. No prompt will give you 100% success, 100% of the time.

I recommend not relying on PR-Agent suggestions to find every possible problem. The code suggestions are ... suggestions.
Use them as an extra reviewer to improve the code, but not as a replacement for baseline human inspection.

**Comment by esauser** [comment]
We are not relying on them for anything, we are using them as an extra tool.  The point I'm trying to make is that for a very large PR it makes sense to get more suggestions, and for a very small PR it makes sense to get less suggestions.  There ought to be a way to navigate this.

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/issues/221#issuecomment-1685256873

**Comment by zmeir** [comment]
I agree with @esauser, and also wanted to add that `num_code_suggestions` configuration with large values (50) just to see what it does, and in moderate PRs (100-ish lines) it doesn't "explode" - it just gives my a few code suggestions, but it's usually capped at around 10 and doesn't actually reach 50. That is it say - it looks like the "up to" part of the prompt is really taken into account (at least in these cases).

**Comment by mrT23** [comment]
@esauser 
this tool ("/improve --extend"):
https://github.com/Codium-ai/pr-agent/pull/229

Should address all the issues you raised:

It allows for:
- no compression of diff files
- generates code suggestions for each group of diff files, and aggregates these suggestions. 
- rank and sort suggestions based on their importance 
- clip the least important suggestions.
