### ISSUE TITLE
[Issue]: Handle PRs on GitHib with many changes

### ISSUE THREAD

**Issue by dwertent** [Codium-ai/pr-agent#169]
First, I love this project! It checked a few boxes I was looking for to automate the code reviews.
I'm more than willing to partner with you to enhance this project.

I've been testing this and noticed that the `/improve` comment does not work on PRs with many changes.
Here is an [example](https://github.com/kubescape/kubescape/pull/1320#issuecomment-1662287017).

**Comment by idavidov** [comment]
just to confirm - you commented /improve and it only generated "Preparing review..." message and nothing more happened, right?

**Comment by hussam789** [comment]
@dwertent Thanks for reporting, we are checking the issue

**Comment by mrT23** [comment]
i am fixing it

**Comment by mrT23** [comment]
@hussam789 
https://github.com/Codium-ai/pr-agent/pull/170

**Comment by mrT23** [comment]
p.s
@dwertent with or without PR-Agenet, a PR of 80 files is a problematic PR ...   :-)

**Comment by dwertent** [comment]
@mrT23 I agree. I've always said my team's motto should be 'Go big or go home!' 😜 I completely agree with you – 80 files might be a tad overenthusiastic.
Thanks for fixing the issue :)
