### ISSUE TITLE
skip the creation of the summary in a specific file type

### ISSUE THREAD

**Issue by kuzeofficial** [Codium-ai/pr-agent#18]
Hello, excellent project, my congratulations to all contributors, just one question at the moment are you planning to add a parameter or some configuration to skip the analysis or summary of a specific file type, example of command:

```--skip-files *.snap```

**Comment by hussam789** [comment]
Thanks @kuzeofficial for the suggestion.
First, we exclude bad extensions listed [here](https://github.com/Codium-ai/pr-agent/blob/1cedd13cf3a47ed8a3300d29170baa87df6d5859/pr_agent/algo/language_handler.py#L8C1-L8C15), if you think we should always skip `.snap` files we can just add it to the bad extensions.

But nevertheless, In general think it's a good feature and I think we should add it where you can skip the analysis of a specific type.
for instance `yaml` files is very common but they are not part of `bad extensions` list, so we can give the developer the choice to exclude them from the PR Review/Q&A.

**Comment by kuzeofficial** [comment]
thanks so much, that's awesome, i'd like to see this suggestion as a feature in the future, for the moment i'll settle for adding it in the bad extension!

**Comment by hussam789** [comment]
Done, `.snap` files will be excluded! 
We will add `--skip-extensions` feature soon
