### ISSUE TITLE
Unable to generate summary in github

### ISSUE THREAD

**Issue by saumilsdk** [Codium-ai/pr-agent#195]
Got below error while running:

**python cli.py --pr_url="https://github.com/XXX/pull/17" describe**

```
    changes in file: No changes were made to the file. stop
INFO:root:Preparing answer...
ERROR:root:Failed to parse AI prediction: while scanning a simple key
  in "<unicode string>", line 5, column 1:
    The PR changes the filename of a ...
    ^
could not find expected ':'
  in "<unicode string>", line 6, column 1:
    PR Main Files Walkthrough:
    ^
INFO:root:Successfully parsed AI prediction after removing 6 lines
INFO:root:Pushing answer...
```

**Comment by saumilsdk** [comment]
@okotek it is our org private repo but it is happening when PR Title value has ":"

e.g. PR Title: PROJ-324: Need to handle special characters

**Comment by mrT23** [comment]
@saumilsdk thanks for the feedback. will take a look

**Comment by okotek** [comment]
I wasn't able to reproduce this, do you mind sharing the result AI completion? I'm not sure that your solution would work for the general case of malformed YAML
