### ISSUE TITLE
.NET C# support plans or ETA?

### ISSUE THREAD

**Issue by rzechu** [Codium-ai/pr-agent#198]
As topic says, would you ever consider supporting .NET C# 4.8 / 6.0 ?

**Comment by rzechu** [comment]
![image](https://github.com/Codium-ai/pr-agent/assets/45091660/dd374062-cc75-4170-bbbc-0229641f63c9)

**Comment by okotek** [comment]
That refers to the CodiumAI plugin, pr-agent would work on C#, go ahead and try

**Comment by micahosborne** [comment]
i can't find anything in the rider plugin that supports c#.  disappointing
