### ISSUE TITLE
[Feature Request] Support for custom templating for "/describe"

### ISSUE THREAD

**Issue by KalleV** [Codium-ai/pr-agent#213]
I've been running the "/describe" on a lot of PRs, and the output is excellent. With reviews automatically being created by the PR Agent, this one has been my primary shortcut. One usability issue I'm running into, however, is that the "/describe" replaces the entire PR description section and title.

The ["/describe -c"](https://github.com/Codium-ai/pr-agent/commit/4aa54b9bd44a13a5d58e95cf3165be6f1923e861) option for posting the description as a comment works as expected, but what I'd really like to do is automate the process of manually filling out Github [pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).

For a possible implementation, it seems like trying to automatically map the LLM response to a dynamically configured pull request template would have too many edge cases. Instead, what if there was support for short-code or variable expansion mechanisms such as: `pr_agent:describe`, and then the AI could substitute the variable with the description?

**Comment by tjwp** [comment]
Yes! I've been thinking about similar things. Many of our repos include a `.github/PULL_REQUEST_TEMPLATE.md`. I was thinking about experimenting with a separate command/prompt that would pull that template for a repo (if it exists) and attempt to generate a description based on that format.

The short-code expansion is also interesting. This is similar to the "markers" that [Copilot for Pull Requests](https://githubnext.com/projects/copilot-for-pull-requests) uses.

**Comment by ShaiGilboa** [comment]
agreed! this will be great! 
for example, we always put a link to the related ticket in the PR description, but the `/describe` is removing it 😅

**Comment by ShaiGilboa** [comment]
I will also add an option to template the title of the PR, again, we always add the related ticket number to the PR title, and the `/describe` removes it

**Comment by Varun-Mullins** [comment]
I spotted a possible problem with the `/describe -c` feature for the generated PR description. I had some screenshots in my PR descriptions before adding the `/describe -c`. But it seems to have replaced the screenshots with the generated description. Don't know if that's a bug or if that was intended.
Thanks!

**Comment by KalleV** [comment]
I'm not sure when it was added but I found the "pr_description.add_original_user_description" and "pr_description.keep_original_user_title" PR agent config options and it's helping a lot with this issue.

Example:
```
/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true
```

Github action version (defaulting "add_original_user_description" as true for repo using `/describe`):
```
PR_DESCRIPTION.ADD_ORIGINAL_USER_DESCRIPTION: true
```

Some kind of templating / short-code expansion support would still be useful for more advanced customization but these options are helping a lot already!
