### ISSUE TITLE
Support Azure OpenAI API Type

### ISSUE THREAD

**Issue by zmeir** [Codium-ai/pr-agent#23]
Do you plan on adding support for customizing openai API setting?

More specifically, will it be possible to control the openai api_type and api_base properties to run against Azure OpenAI? Similarly to how this is done when using the `openai` package directly:
```python
import openai
# This is set to `azure`
openai.api_type = "azure"
# The API key for your Azure OpenAI resource.
openai.api_key = os.getenv("OPENAI_API_KEY")
# The base URL for your Azure OpenAI resource. e.g. "https://<your resource name>.openai.azure.com"
openai.api_base = os.getenv(" OPENAI_API_BASE ")
# OpenAI API Version
openai.api_version = os.getenv(" OPENAI_API_VERSION")
```

**Comment by hussam789** [comment]
Sure, thanks for suggesting @zmeir

**Comment by okotek** [comment]
Definitely, we'll add it next week

**Comment by okotek** [comment]
https://github.com/Codium-ai/pr-agent/pull/40
@hussam789
