### ISSUE TITLE
[Bug] improve --extended does nothing

### ISSUE THREAD

**Issue by esauser** [Codium-ai/pr-agent#236]
I've tried to use the new `improve --extended` twice now and next to nothing happens.  All I get are the eye emojis, nothing else occurs.  How can we determine if it's working?  Regular `/improve` is working as expected.

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/pull/246#issuecomment-1694593269 (for example)

`/improve --extended` works
