### ISSUE TITLE
[Feature request] Azure API not well supported / documented

### ISSUE THREAD

**Issue by TomDarmon** [Codium-ai/pr-agent#245]
Hello!

I am currently learning how to use a PR agent. I would like to use the Azure API instead of the OpenAI key using GitHub Actions.

There is no documentation available, but it seems that the code can be modified locally with minor adjustments to make it work.
It appears that with minimal effort, it could be added for the GitHub Actions deployment method.

I believe there are two changes that need to be made to make it possible:
- The `AiHandler` needs to dynamically set the `azure` attribute based on a configured value to specify Azure deployment.
- The appropriate API variables, such as `open_ai.api_base` and `open_ai.api_version`, should be passed as GitHub Actions secrets/configurations.

```python
class AiHandler:
    """
    This class handles interactions with the OpenAI API for chat completions.
    It initializes the API key and other settings from a configuration file,
    and provides a method for performing chat completions using the OpenAI ChatCompletion API.
    """

    def __init__(self):
        """
        Initializes the OpenAI API key and other settings from a configuration file.
        Raises a ValueError if the OpenAI key is missing.
        """
        try:
            openai.api_key = get_settings().openai.key
            litellm.openai_key = get_settings().openai.key
            litellm.debugger = get_settings().config.litellm_debugger
            self.azure = False # <--- HARDCODED HERE
            ...
``` 

I'm new to the repository so I'm unsure if I'm missing something, if it's already possible to use the azure API using github actions I would be super grateful if you could document it 🙏

**Comment by okotek** [comment]
Hi @TomDarmon 
See the discussion [here](https://github.com/Codium-ai/pr-agent/pull/172) regarding Azure support. 
self.azure is not hard coded to False, it is activated when the API_TYPE flag is set to "azure". 
```
            if get_settings().get("OPENAI.API_TYPE", None):
                if get_settings().openai.api_type == "azure":
                    self.azure = True
                    litellm.azure_key = get_settings().openai.key
```

Fill in the commented fields in the configuration file (.secrets.toml) or through environment variables.

[openai]
key = ""  # Acquire through https://platform.openai.com
#org = "<ORGANIZATION>"  # Optional, may be commented out.
# Uncomment the following for Azure OpenAI
#api_type = "azure"
#api_version = '2023-05-15'  # Check Azure documentation for the current API version
#api_base = ""  # The base URL for your Azure OpenAI resource. e.g. "https://<your resource name>.openai.azure.com"
#deployment_id = ""  # The deployment name you chose when you deployed the engine
#fallback_deployments = []  # For each fallback model specified in configuration.toml in the [config] section, specify the appropriate deployment_id

**Comment by TomDarmon** [comment]
So if I understand correctly, by just just setting the env variables like this it should work ?

```python
on:
  pull_request:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          API_TYPE: "azure"
          DEPLOYMENT_ID: "gpt-4" # custom name of the deployed model on Azure
          OPENAI_KEY: ${{ secrets.AZURE_API_KEY }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
```

**Comment by okotek** [comment]
We use Dynaconf for configuration, the syntax for environment variables is <SECTION>.<KEY>, so you should add "OPENAI." for the OpenAI variables, for example:
OPENAI.API_TYPE: "azure"

**Comment by ishaan-jaff** [comment]
@TomDarmon I'm the maintainer of LiteLLM - was this solved for you ? 

Here's how azure calls work with litellm
```python
from litellm import completion
response= completion('your-azure-deployment-name', messages, custom_llm_provider="azure")
```

Make sure your .env contains the following variables:
os.environ['AZURE_API_KEY'],os.environ['AZURE_API_BASE'],os.environ['AZURE_API_VERSION']

Here's a link to our docs 
https://docs.litellm.ai/docs/completion/supported#azure-openai-chat-completion-models 

Here's my calendly: happy to hop on a call and help out :https://calendly.com/ishaan-berri/30min

**Comment by mrT23** [comment]
Similar Issues:

1. [Support Azure OpenAI API Type](https://github.com/Codium-ai/pr-agent/issues/23)

2. [Running Github Action: openai.error.RateLimitError](https://github.com/Codium-ai/pr-agent/issues/104)

**Comment by krrishdholakia** [comment]
@mrT23 @TomDarmon i'll make a PR to improve docs on this

**Comment by krrishdholakia** [comment]
Made a PR for this - https://github.com/Codium-ai/pr-agent/pull/276

**Comment by krrishdholakia** [comment]
Can we close this now as the PR has been merged @TomDarmon @mrT23
