### ISSUE TITLE
unable to override pr_commands

### ISSUE THREAD

**Issue by tjwp** [Codium-ai/pr-agent#247]
I'm facing a challenge with the `github_app.pr_commands` configuration:

https://github.com/Codium-ai/pr-agent/blob/56828f01707ea7110091df7d37b15282645df3c8/pr_agent/settings/configuration.toml#L66-L69

These commands are invoked for any of the [`handle_pr_actions`](https://github.com/Codium-ai/pr-agent/blob/56828f01707ea7110091df7d37b15282645df3c8/pr_agent/settings/configuration.toml#L65) (also a List):

https://github.com/Codium-ai/pr-agent/blob/56828f01707ea7110091df7d37b15282645df3c8/pr_agent/servers/github_app.py#L125

I believe the problem is that with Dynaconf `merge_enabled=True` additional configuration files cannot remove values from the List only append to it:

https://github.com/Codium-ai/pr-agent/blob/56828f01707ea7110091df7d37b15282645df3c8/pr_agent/config_loader.py#L13

This is okay for the `/auto_review` before there is a separate `pr_reviewer.automatic_review` configuration that can be used to disable the command. Similar `automatic_*` configurations could be added for the other commands but it seems a poor design choice requiring the implementer to know which commands have accumulated in the list and then disable the ones that are not wanted.

If there is a way to override `github_app.pr_commands` (without setting `merge_enabled` to False which looks like it would be problematic for combining configuration from multiple files), please let me know!

## Proposed solution

If it is not possible to override `pr_commands`, then I suggest removing `pr_commands` and having an `automatic_<command>` configuration for commands that might run on pull request events. The `automatic_*` configuration would be instead of, not in addition to, `pr_commands`.

I do like the fact that the existing `pr_commands` also allows configuration options to be passed to the commands that are automatically run on PRs. An extension of what I've proposed here would be to support an `automatic_options` configuration for each command that could run on a pull request. This would be the configuration that is used for automatic PR events and might differ from the default configuration if the command is invoked manually.

## Summary

Configuration using lists with Dynaconf seems problematic for supporting overrides and customization. It would be better to only use values that can be overridden, possibly multiline strings that could be split or dictionaries that can be modified.

**Comment by okotek** [comment]
Can you explain the rational of specifying configuration options on the command line rather than specifying them in the configuration file directly?

**Comment by mrT23** [comment]
@tjwp 
please take a look at the functionality presented in:
https://github.com/Codium-ai/pr-agent/blob/tr/github_app/CONFIGURATION.md#working-from-github-app-pre-built-repo

It enables to overwrite any configuration parameter in github_app

**Comment by tjwp** [comment]
Thanks for the pointer. My problem is that with `pr_commands` set in the `configuration.toml`:

https://github.com/Codium-ai/pr-agent/blob/aa03654ffcbf7f38b25f9da9b6653e9c95c2e993/pr_agent/settings/configuration.toml#L66-L69

The `pr_commands` value can only be extended, not replaced, by `.pr_agent.toml`. So for example if `/describe` is included in the default value in `configuration.toml`, then there is no way turn it off for a specific repo.

**Comment by okotek** [comment]
Thanks, we merged a fixed to this issue, .pr_agent.toml will take precedence over the pr_command parameters.

**Comment by mrT23** [comment]
Similar Issues:

1. [In-line PR comments sometimes request redundant changes](https://github.com/Codium-ai/pr-agent/issues/137)

2. [Failure in `/improve` command](https://github.com/Codium-ai/pr-agent/issues/221)

3. [[Feature Request] - Ability to configure GitHub App](https://github.com/Codium-ai/pr-agent/issues/155)
