### ISSUE TITLE
Customs LLMs

### ISSUE THREAD

**Issue by uripeled2** [Codium-ai/pr-agent#25]
Do you have any plans to add configuration options that would allow the use of custom LLMs in future versions?
I recently published a package [llm-client](https://github.com/uripeled2/llm-client-sdk) that can be very helpful in enabling the support to run other LLM models, including OpenAI, Google, AI21, HuggingfaceHub, Aleph Alpha, Anthropic, Local models with transformers.

**Comment by coditamar** [comment]
👍
It is in the roadmap
https://github.com/Codium-ai/pr-agent#roadmap

Would you like to integrate llm-client into pr-agent?

**Comment by uripeled2** [comment]
Why did you mark this as completed? @mrT23

**Comment by mrT23** [comment]
You didnt respond to the question, so i closed the issue.
I can keep it open

**Comment by uripeled2** [comment]
I don’t have time to make the integration, but I will be happy to help if needed.

**Comment by mrT23** [comment]
see https://github.com/Codium-ai/pr-agent/pull/172
