### ISSUE TITLE
[Bug] Rerunning /describe after adding new changes does not always update the "PR Main Files Walkthrough" section

### ISSUE THREAD

**Issue by KalleV** [Codium-ai/pr-agent#254]
I've been noticing that re-running the `/describe` operation through Github issue comments is not updating the "PR Main Files Walkthrough" section whereas it seems to update the description each time if there are new changes. I didn't try to trace the root cause yet but this is particularly noticeable if you commit a change to a file that is entirely removed in a subsequent commit on the same branch.

**Comment by mrT23** [comment]
Thanks for the feedback.

I Think this happens because we (@zmeir  :-) ) are adding the previous description to the prompt, and it can confuse the model.

I think I will add an option to fully ignore the previous description, and it will help this kind of scenario

**Comment by zmeir** [comment]
Interesting find. I think we can address this by only using the original user description for the describe prompt instead of using the whole PR-Agent generated description.

@mrT23 if you think that's a good approach I can try working on it. I don't think it should be too complicated.

**Comment by zmeir** [comment]
@mrT23 --> #260
