### ISSUE TITLE
security concern - disable litellm logs by default

### ISSUE THREAD

**Issue by sjcotto** [Codium-ai/pr-agent#257]
Hi: 

how to disable the sending logs? was using the docker command

docker run --rm -it -e OPENAI.KEY=Q -e GITHUB.USER_TOKEN=X codiumai/pr-agent --pr_url https://github.com/organization/repo/x/pull/xxx review

and notice the request and response from to open AI was logged in https://admin.litellm.ai/ quite publickly 

i think this is not a good default behavior and can bring big security concerns, going to this URL https://admin.litellm.ai/ anyone can see all the request response to open AI

**Comment by sjcotto** [comment]
also email are logged there in a public way associated with prompts 

<img width="1132" alt="Screenshot 2023-08-28 at 13 17 04" src="https://github.com/Codium-ai/pr-agent/assets/3880470/e49fef6d-5b10-4188-9238-b13739c22724">

**Comment by krrishdholakia** [comment]
If you can tell me your litellm version I can see what might be causing this - @mrT23 i'll also check the default version of litellm on pr-agent and bump it if necessary to make sure these are **not** getting logged.

**Comment by krrishdholakia** [comment]
Submitted a PR to deal with this. https://github.com/Codium-ai/pr-agent/pull/259

This is exactly how logging should work - it is by default opt-in: https://github.com/BerriAI/litellm/blob/c008a035c8a79bc22a5e3abf8e1894fc35cb4d05/litellm/utils.py#L437


I'm incredibly sorry for this issue @sjcotto @mrT23

**Comment by mrT23** [comment]
Thanks for quickly addressing it

**Comment by sjcotto** [comment]
Thanks!
