### ISSUE TITLE
Documentation: Github actions?

### ISSUE THREAD

**Issue by bob-hinrichs** [Codium-ai/pr-agent#26]
Is there possibly a way to use this with a github action, that would avoid having to run on a separate server? Perhaps it could be triggered upon creation of a PR, then use something like perhaps https://github.com/marketplace/actions/add-pr-comment to automatically add an evaluation? Or perhaps there is an even better way, that's just a thought.

**Comment by mrT23** [comment]
@okotek any thoughts?

**Comment by okotek** [comment]
It should work, it's actually a great idea. I'll add it to our backlog

**Comment by akotek** [comment]
requires some effort to setup without any GH support, +1 here

**Comment by okotek** [comment]
https://github.com/Codium-ai/pr-agent/pull/47

**Comment by okotek** [comment]
#53
