### ISSUE TITLE
CodiumAI on pycharm cannot log in

### ISSUE THREAD

**Issue by RuoCJ** [Codium-ai/pr-agent#284]
As shown in the question, after I downloaded the plug-in and installed it, I clicked to log in through github. After authorization, I could not jump from github to pycharm. It was always displayed that the plug-in was being loaded, but vscode could

I tried Google Browser and Microsoft edge respectively

My pycharm version：PyCharm 2022.3.2 (Professional Edition)
My system is windows10

**Comment by mrT23** [comment]
please share this on:
https://discord.com/channels/1057273017547378788/1075012292854435840

This repo is for pr-agent, not CodiumAI plugin

**Comment by ArtsiomCh** [comment]
Hi @RuoCJ 
Looking into our logs I see some KeyChainCredentialStore related errors. Did you (during login process) reject/skip any Mac OS request related to saving token into CredentialStore?
If so, try login again and accept such request if happened. If still having same issue check please if you did permanently restrict access to CredentialStore for IDE and allow it.
PS If still experience this (or any other) issue, please report at [JetBrains plugin bug tracker](https://github.com/Codium-ai/codiumai-jetbrains-release/issues)
