### ISSUE TITLE
local provider requires pr-url

### ISSUE THREAD

**Issue by anthonym21** [Codium-ai/pr-agent#286]
What's are the command line parameters when provider = local?

**Comment by mrT23** [comment]
Similar Issues:

1. [Bitbucket docs](https://github.com/Codium-ai/pr-agent/issues/207)

2. [Support for other git providers like Azure Repos](https://github.com/Codium-ai/pr-agent/issues/174)

3. [PR description using commit messages may produce wrong results](https://github.com/Codium-ai/pr-agent/issues/179)

4. [Failure in `/improve` command](https://github.com/Codium-ai/pr-agent/issues/221)

**Comment by krrishdholakia** [comment]
hey @anthonym21 how're you calling your local provider? is it localhost api endpoint?
