### ISSUE TITLE
[Feature Request] Estimated Time to Review (ETR)

### ISSUE THREAD

**Issue by Archetypically** [Codium-ai/pr-agent#303]
A great value-add feature would be an **estimated time to review** that the agent could generate. 
This could be based on whatever the model thinks is a significant metric (lines of code changed, types of files changed, number of files changes, deletions vs. modifications vs. additions, etc). 

This is valuable from the perspective of the PR author by having some feedback if a PR is going to feel "too big" to review (and therefore the downstream action would be to break up the PR into multiple PRs).

Additionally, this would help reviewers by addressing that cognitive load of "this PR will take forever to review" which might negatively impact the responsiveness of the reviewer.

---

<sup>Suggested post here by @tjwp</sup>

**Comment by mrT23** [comment]
@Archetypically your observation regarding the fact the LLMs are better in comparing and ranking than in giving absolute values is correct. i will adopt the prompt

i think the t-shrit size is a bit cumbersome and an unintuitive ranking option, both for the LLM, and a human. Why not just a number - "review effort, on a scale of 1-5" ?

Regarding ignoring certain types - we already do that, see 'pr_agent/settings/language_extensions.toml'. you are welcome to open a PR with more types,  or dynamically edit the 'extra' field.
Note that some types are ambiguous. Will you ignore .yaml files ? Sometimes they are auto-generated. Sometimes not. you can also tell the mode to ignore your specific types in the 'extra instruction' prompt

**Comment by mrT23** [comment]
in any case, since this is a nice feature, I think I will turn it on by default. thanks for the suggestion @Archetypically 
If you will use it, welcome to share in the future additional feedback for tuning and optimizing the prompt.

merged https://github.com/Codium-ai/pr-agent/pull/306
