### ISSUE TITLE
[Bug] GitHub does not return languages for some large repos

### ISSUE THREAD

**Issue by tjwp** [Codium-ai/pr-agent#305]
The GitHub [languages endpoint](https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#list-repository-languages) for a repo used here can return an empty response for very large repos:

https://github.com/Codium-ai/pr-agent/blob/279d45996fbc9ea70c1269ad1fca270782832b08/pr_agent/git_providers/github_provider.py#L230

An empty result for languages currently prevents some further processing of the pull request, e.g. no walkthrough for PR description. 

This could be addressed by skipping file sorting if there are no languages, or allowing the languages weighting to be provided via configuration if it cannot be fetched via API.

**Comment by mrT23** [comment]
can you share an example for a public repo where we get an empty response ?

**Comment by tjwp** [comment]
> can you share an example for a public repo where we get an empty response ?

I don't know of an example public repo. If I come across one, I'll post it. I think they should be easy to spot because `Languages` will not appear for the repository in the web UI. The symptom is that the `get_languages()` call above returns an empty Dictionary `{}`.

**Comment by mrT23** [comment]
i am not sure if this is a property of "big" repos, or repos that for some reason disabled usage of the language feature.

in any case, handled this In https://github.com/Codium-ai/pr-agent/pull/306

**Comment by tjwp** [comment]
Thanks for fix!
