### ISSUE TITLE
Trigger multiple PR-Agent command on GitHub Actions pull request event

### ISSUE THREAD

**Issue by okotek** [Codium-ai/pr-agent#309]
This is implemented for GitHub App, can be useful also for GitHub action. Requires the following:
1. Add "pr_commands" in the [github_actions] section in configuration.toml (create it since it doesn't exist).
2. Copy/reuse the logic from github_app.py to github_action_runner.py.

**Comment by sarbjitsinghgrewal** [comment]
### Similar Issues
___

1. **[unable to override pr_commands](https://github.com/Codium-ai/pr-agent/issues/247)** (score=0.86)

2. **[Activate pr-agent on this repository as a GitHub app](https://github.com/Codium-ai/pr-agent/issues/37)** (score=0.86)

3. **[Adding Descriptive Comments or Reviews Directly Upon PR Creation](https://github.com/Codium-ai/pr-agent/issues/326)** (score=0.85)

4. **[[Feature Idea / Documentation] PR Agent interacts well with Github Saved Replies](https://github.com/Codium-ai/pr-agent/issues/201)** (score=0.84)

**Comment by sarbjitsinghgrewal** [comment]
### Similar Issues
___

1. **[unable to override pr_commands](https://github.com/Codium-ai/pr-agent/issues/247)** (score=0.86)

2. **[Unable to overwrite github_app.pr_commands](https://github.com/Codium-ai/pr-agent/issues/372)** (score=0.86)

3. **[Activate pr-agent on this repository as a GitHub app](https://github.com/Codium-ai/pr-agent/issues/37)** (score=0.86)

4. **[Adding Descriptive Comments or Reviews Directly Upon PR Creation](https://github.com/Codium-ai/pr-agent/issues/326)** (score=0.85)

**Comment by mrT23** [comment]
### Similar Issues
___

1. **[unable to override pr_commands](https://github.com/Codium-ai/pr-agent/issues/247)** (score=0.86)

2. **[Unable to overwrite github_app.pr_commands](https://github.com/Codium-ai/pr-agent/issues/372)** (score=0.86)

3. **[Adding Descriptive Comments or Reviews Directly Upon PR Creation](https://github.com/Codium-ai/pr-agent/issues/326)** (score=0.85)

4. **[[Feature Idea / Documentation] PR Agent interacts well with Github Saved Replies](https://github.com/Codium-ai/pr-agent/issues/201)** (score=0.84)

**Comment by mrT23** [comment]
### Similar Issues
___

1. **[unable to override pr_commands](https://github.com/Codium-ai/pr-agent/issues/247)** (score=0.86)

2. **[Unable to overwrite github_app.pr_commands](https://github.com/Codium-ai/pr-agent/issues/372)** (score=0.86)

3. **[Activate pr-agent on this repository as a GitHub app](https://github.com/Codium-ai/pr-agent/issues/37)** (score=0.86)

4. **[Adding Descriptive Comments or Reviews Directly Upon PR Creation](https://github.com/Codium-ai/pr-agent/issues/326)** (score=0.85)

**Comment by mrT23** [comment]
### Similar Issues
___

1. **[unable to override pr_commands](https://github.com/Codium-ai/pr-agent/issues/247)** (score=0.86)

2. **[Unable to overwrite github_app.pr_commands](https://github.com/Codium-ai/pr-agent/issues/372)** (score=0.86)

3. **[Activate pr-agent on this repository as a GitHub app](https://github.com/Codium-ai/pr-agent/issues/37)** (score=0.86)

4. **[Adding Descriptive Comments or Reviews Directly Upon PR Creation](https://github.com/Codium-ai/pr-agent/issues/326)** (score=0.85)
