### ISSUE TITLE
[Bug] PR agent crashing when no code suggestion can be given.

### ISSUE THREAD

**Issue by TomDarmon** [Codium-ai/pr-agent#311]
Hello, the PR agent github action is working correctly on most of my commands.

But on a long PR, the agent didn't produce any code suggestions and made the code crash:

![image](https://github.com/Codium-ai/pr-agent/assets/36815861/81bdf52e-14fd-41c1-b874-1ded2f1bde73)

Additionally, do you keep track of stable versions which I can pin my version to ?

**Comment by mrT23** [comment]
@TomDarmon  thanks for the feedback.
i will add protection for no code suggestion

regarding stable versions, we are aware that working only against some unknown 'latest' docker is not optimal.
we plan to release the first stable version tomorrow, and follow this methodology.

**Comment by mrT23** [comment]
@TomDarmon addressed in https://github.com/Codium-ai/pr-agent/pull/312

**Comment by TomDarmon** [comment]
Thank you for the reactivity!
