### ISSUE TITLE
I want pr-agent not push anything on github but just provide it output 

### ISSUE THREAD

**Issue by vlorenzo** [Codium-ai/pr-agent#316]
Hi, 
running pr-agent CLI 
I would like the option to have pr-agent not push anything on github but just provide its output.

Is that possible?
Thanks!

**Comment by mrT23** [comment]
yes
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-from-a-local-repo-cli
(note 2)

**Comment by vlorenzo** [comment]
thank you!
