### ISSUE TITLE
Feature request: PR changes via comment from a comment

### ISSUE THREAD

**Issue by zackproser** [Codium-ai/pr-agent#325]
Thanks for open-sourcing PR-agent! 🙌

It appears that this would either be an extension of the /improve command or a separate complimentary command, but my ideal workflow would be to have PR-agent enabled on certain repos where I could ask for several high level tasks to be performed on my branch as a follow up commit. 

Example requests:

- Delete the third image in my blog post
- Rewrite the final paragraph for clarity on X, Y, Z
- Rewrite function X using the async/await or try/catch patterns
- etc

Ideally, PR-agent would then check out my latest code, load it into context somehow and make my requested changes as a follow up commit that I could review. 

It might also make sense to have /revert commands in this workflow. 

If I had this, I could close the mobile editing loop on my blog, which uses Vercel and thereby creates preview environments for each commit.

**Comment by mrT23** [comment]
Hi @zackproser 

Thanks for the insightful suggestion. However, i believe it is out-of-scope for **PR**-Agent project, which deals with Pull Requests code change (PR).

Doing general code changes to a big repo, from a simplistic command (rewrite function ...) is a gigantic task. Currently, from my tests and experiments, solutions that are tailored exactly to do that are doing a mediocre job, at best. i personally tested [sweepAI](https://github.com/sweepai/sweep), and found it unreliable. For any non-trivial change, they usually fail, and in general, I found no 'energetic gain' from working with those complicated (and expensive) tools.

In the scope of PR-Agent, implementing user commands **that are related specifically to the code change in the PR** might be possible. For example - 'add docstring to the new function that was added in the PR', sound reasonable, and can offer more reliable results.

**Comment by zackproser** [comment]
> Hi @zackproser
> 
> Thanks for the insightful suggestion. However, i believe it is out-of-scope for **PR**-Agent project, which deals with Pull Requests code change (PR).
> 
> Doing general code changes to a big repo, from a simplistic command (rewrite function ...) is a gigantic task. Currently, from my tests and experiments, solutions that are tailored exactly to do that are doing a mediocre job, at best. i personally tested [sweepAI](https://github.com/sweepai/sweep), and found it unreliable. For any non-trivial change, they usually fail, and in general, I found no 'energetic gain' from working with those complicated (and expensive) tools.
> 
> In the scope of PR-Agent, implementing user commands **that are related specifically to the code change in the PR** might be possible. For example - 'add docstring to the new function that was added in the PR', sound reasonable, and can offer more reliable results.

Roger - thanks for your thoughtful reply - what you say makes sense to me. For my current use case, I believe updates scoped solely to the changes in the current PR would work.

**Comment by mrT23** [comment]
👍
