### ISSUE TITLE
[Feature Request] Allow specifying an additional path or paths to extra code context

### ISSUE THREAD

**Issue by georgeseifada** [Codium-ai/pr-agent#333]
Overall, PR Agent gives great suggestions. There are some cases where the suggestions and responses to questions could be even better if it had more context beyond just the code in the PR. E.g. if the user can supply additional code for context through a flag like `--extra_context`. It can be a file(s), folder(s), or the whole repo (assuming it's small enough, and in some cases the user can use gpt-4 32k context or anthropic 100k context to capture it).

**Comment by mrT23** [comment]
Hi @georgeseifada 

Every tool in pr-agent, including the code suggestion, has an optional parameter called `--extra-instructions`.
see an example in: https://github.com/Codium-ai/pr-agent/issues/318#issuecomment-1729673468
you can use this parameter to give extra code, with instructions on what to do with it ("make sure the PR uses the same formatting style as the following code: ... ")

Processing an entire repo is out-of-scope of PR-Agent, and is usually way way above any reasonable token limit (rule-of-thumb - 1000 lines == 10K tokens).
In addition, extra context code should be accompanied by extra instructions to the model, on how to utilize this extra code.

Hence, I think the `--extra-instructions` field is a reasonable solution

**Comment by georgeseifada** [comment]
Alright. Will give that one a try. Thank you!

**Comment by mrT23** [comment]
see https://github.com/Codium-ai/pr-agent/blob/main/docs/IMPROVE.md
If you are not interested in PR-Compression, use `/improve --extended`

specific answers
1) you are welcome to open a PR, to make it adjustable.
PATCH_EXTRA_LINES = 3

2) yes. you can work with any model, including   'claude-2': 100000,
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/__init__.py
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#appendix---additional-configurations-walkthrough

3) small means that the number of tokens (with expand) is below the token limit of the model

**Comment by mrT23** [comment]
i am closing the issue. re-open it if still relevant
