### ISSUE TITLE
Not getting codium commands for PR agent on bitbucket

### ISSUE THREAD

**Issue by praveenpnj94** [Codium-ai/pr-agent#334]
Even after updating bitbucket pipeline and adding repository variables, unable to get codium commands.
<img width="1193" alt="Screenshot 2023-09-28 at 2 52 57 AM" src="https://github.com/Codium-ai/pr-agent/assets/13162677/4b870407-f653-478a-8545-3613f322cbb8">

**Comment by praveenpnj94** [comment]
Getting the below while running through docker

![Uploading Screenshot 2023-09-28 at 5.44.31 AM.png…]()

**Comment by mrT23** [comment]
please remove _immediately_ all duplicate issues (discord)


What do you mean "unable to get codium commands." ?
When you post a comment "/describe", what happens ? share a proper log message, with full details

**Comment by praveenpnj94** [comment]
Sure, added in discord in support channel if anyone else faced the same. Will remove those.

So, I wanted to integrate the Codium PR agent with the bitbucket. The goal and expectation was that PR review comments will be added or summary will be provided on the PR when PR gets generated, either automatically or through commands like "/describe" or "/review". So, I followed the instructions mentioned in the documentation https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#method-9-run-as-a-bitbucket-pipeline

Also while creating bitbucket bearer token, I set the repository access to Read (Did I also need to give access for Pull requests to read?) 

I used the openai API key generated from my free account. (Dis I need to use gpt pro paid API key?)

After I was done and when I raised the PR , no summary/review was generated automatically. Even when I start typing "/describe" no menu options come and when I press enter, nothing happens
<img width="1464" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/13162677/479ae78e-4643-4b6c-ad36-832a67e6ce78">

Then I thought to follow the steps mention here with method 1 
https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#method-1-use-docker-image-no-installation-required
 But it didn't work as well and showed the following errors
 
<img width="1481" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/13162677/5778f9a1-2999-4246-8b78-990af3a3ade6">

**Comment by mrT23** [comment]
@sarbjitsinghgrewal 
can you take a look at this issue ? seesms like a problem in bitbucket pipeline, which was approved here https://github.com/Codium-ai/pr-agent/pull/304

**Comment by praveenpnj94** [comment]
Any updates on this?

**Comment by mrT23** [comment]
@praveenpnj94  we apologize, but due to inner constraints only next week we will be able to find time to debug it

**Comment by mrT23** [comment]
@okotek

**Comment by praveenpnj94** [comment]
Did we get any resolution on this?

**Comment by SergioSuarezDev** [comment]
We have the same problem on Bitbucket

**Comment by okotek** [comment]
Fix pending in https://github.com/Codium-ai/pr-agent/pull/386

**Comment by SergioSuarezDev** [comment]
I have recorded a video, using the pr agent as a bitbucket pipeline, only the main review is generated, but commands cannot be added, it doesn't work.
![Uploading Kapture 2023-10-18 at 18.25.04.gif…]()

**Comment by SergioSuarezDev** [comment]
![Kapture 2023-10-18 at 18 25 04](https://github.com/Codium-ai/pr-agent/assets/3636232/3b2b31ac-384f-479a-9bb3-f2ee83155ccc)

**Comment by mrT23** [comment]
@SergioSuarezDev 

Correct. see:
https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#run-as-a-bitbucket-pipeline
