### ISSUE TITLE
[FEATURE REQUEST] Blocking a PR

### ISSUE THREAD

**Issue by DesignMike** [Codium-ai/pr-agent#350]
Is it possible for PR Agent to block the "pass" checks of a PR if there are **critcal** or **important** issues found?

Additionally, is it possible to **bold** and make the font color red for **important** issues? 

PS: I'm using GitHub Actions for my PR Agent

**Comment by mrT23** [comment]
Hi @DesignMike 
'important' or 'critical' issues are subjective. What one will see as critical, other may not.
There will always be false positives and false negatives. Take that into consideration

Regarding blocking:
Not support currently. While technically it might be possible (but requires code changes), I am hesitant about this kind of feature. It seems to me that (always) blocking until a human approves is better. Add a protocol to review pr-agent suggestions before approving

Regarding emphasizing important suggestions:
- I recommend reading the docs for the 'improve' tool: https://github.com/Codium-ai/pr-agent/blob/main/docs/IMPROVE.md
- For example, 'improve --extended' by default sorts the suggestion from most important to least important. So the first suggestions are always the most important ones.
- You can also use the 'extra_instructions' field to better guide pr-agent to what is 'important' in your view, and should be emphasized and higher ranked
- The 'review' tool (https://github.com/Codium-ai/pr-agent/blob/main/docs/REVIEW.md) also has a feature 'require_score_review' which might be useful for you - giving an integral score to the PR. PRs with bad score usually require changes

**Comment by DesignMike** [comment]
Thank you for the helpful and detailed response.

I was able to get it to fail the pass check by editing the pr_agent.yml file and adding a few lines of code.

**Comment by mrT23** [comment]
👍
