### ISSUE TITLE
Inline code suggestions from `/improve` command causing too much noise

### ISSUE THREAD

**Issue by zmeir** [Codium-ai/pr-agent#361]
According to this commented out part, the code suggestions used to be sent to the PR in one request, thus generating one notification. The way it is now written forces multiple code suggestions to be sent in separate requests, each generating a separate GitHub "comment" which triggers a separate notification:
https://github.com/Codium-ai/pr-agent/blob/fd8c90041c730be45df13a1fcd96b6f87a4a2ea0/pr_agent/tools/pr_code_suggestions.py#L141-L145

I tested it with the commented code reverted to its previous state and it worked as expected - all 3 suggestions were posted to my PR in a single review, so I wonder what was the reason to disable this behaviour?
```python
is_successful = self.git_provider.publish_code_suggestions(code_suggestions)
if not is_successful:
    logging.info("Failed to publish code suggestions, trying to publish each suggestion separately")
    for code_suggestion in code_suggestions:
        self.git_provider.publish_code_suggestions([code_suggestion])
```

**Comment by mrT23** [comment]
@zmeir there was a major problem with the previous logic in gitlab, see:
https://github.com/Codium-ai/pr-agent/issues/353

when one of the suggestions was invalid (and it can happen, for example a wrong line), all the other suggestions were still published, yet we also turned to the fallback, so we ended up with each suggestion publishing twice.

i don't like this uncontrolled behavior when on of the suggestions is invalid.

However, I meant to do it only for gitlab. will fix

**Comment by zmeir** [comment]
Thanks @mrT23! Didn't know about the GitLab issue. I'll wait for a fix on your end or try to push one myself if I have the time.

**Comment by mrT23** [comment]
5 minutes :-)

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/pull/363
