### ISSUE TITLE
How to add RAG feature for pr-agent?

### ISSUE THREAD

**Issue by leiwen83** [Codium-ai/pr-agent#365]
I think it maybe useful if pr-agent could do retrieval from external knowledge base.
So could pr-agent be interacted with some like langchain to do the retrieval, and embed corresponding policy into the prompt?

**Comment by mrT23** [comment]
The [/similar_issue ](https://github.com/Codium-ai/pr-agent/blob/main/docs/SIMILAR_ISSUE.md) feature is a RAG-like feature. You are welcome to give it a try

If you have any other concrete suggestions, welcome to share them. 
In general, its debatable how effective is RAG for code, but we are open for (good :-) ) suggestions

**Comment by mrT23** [comment]
i am closing the issue, re-open it if you have specific suggestions
