### ISSUE TITLE
Unable to overwrite github_app.pr_commands

### ISSUE THREAD

**Issue by realDragonium** [Codium-ai/pr-agent#372]
I'm using the Hosted PR-Agent service and I'm trying to overwrite github_app.pr_commands by using `<REPO_ROOT>/.pr_agent.toml`. There is information https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools which say that you can set `pr_commands` to `[]` to cancel the automatic run of all tools. However that doesn't seem to work. 

The file itself does work because I have successfully changed `inline_code_comments`.

The config section itself is, which is copied from https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L71
```
[github_app]
# these toggles allows running the github app from custom deployments
bot_user = "github-actions[bot]"
override_deployment_type = true
# in some deployments it's possible to get duplicate requests if the handling is long,
# these settings are used to avoid handling duplicate requests.
duplicate_requests_cache = false
duplicate_requests_cache_ttl = 60  # in seconds
# settings for "pull_request" event
handle_pr_actions = ['opened', 'reopened', 'ready_for_review', 'review_requested']
pr_commands = []
``` 

But it still runs both `/auto_review` and `/describe` for every PR it creates. 

---

Or did i do something wrong? Or is it perhaps not possible for Hosted PR-Agent?

**Comment by tjwp** [comment]
I think this is the same problem that I wrote about here https://github.com/Codium-ai/pr-agent/issues/247

**Comment by mrT23** [comment]
@realDragonium i think its a parsing issue.
try setting:
`pr_commands = ""`
instead

**Comment by realDragonium** [comment]
Thanks for the quick reaction! 

Changing `pr_commands = []` -> `pr_commands = ""` didn't resolve the issue. Opening a pull request will still trigger the 'default' pr_commands  of `auto_review` and `describe ...`. Even if you change it to `pr_commands = ["/auto_review"]`, it will still run both.


> I think this is the same problem that I wrote about here [247](https://github.com/Codium-ai/pr-agent/issues/247)

It might be! Could it be possible that Codium's Hosted PR-Agent is running on an older version which doesn't contain the fix for that?

**Comment by mrT23** [comment]
@realDragonium can you try once more ? (following https://github.com/Codium-ai/pr-agent/pull/374)

**Comment by realDragonium** [comment]
Yes! Sorry for the delayed response but it works. Thanks!

`pr_commands = []` also works just fine!
