### ISSUE TITLE
Allow Custom Domain URLs for Azure DevOps Integration

### ISSUE THREAD

**Issue by moccajoghurt** [Codium-ai/pr-agent#380]
Please update the script to accommodate custom domain URLs for Azure DevOps integration, instead of strictly enforcing the "azure.com" domain. Our organization utilizes a custom URL, https://tfs.mycompany.com/, for Azure DevOps access, but the current script rejects this URL format. This modification will enable a broader range of configurations and cater to organizations with custom domain setups for Azure DevOps. 

Thank you.

https://github.com/Codium-ai/pr-agent/blob/428c38e3d90fe26f70518c7f97c94284421c79a2/pr_agent/git_providers/azuredevops_provider.py#L239C9-L239C9

**Comment by mrT23** [comment]
merged
