### ISSUE TITLE
Bitbucket pipeline error

### ISSUE THREAD

**Issue by SergioSuarezDev** [Codium-ai/pr-agent#384]
We have this error trying to add bitbucket following this  method (9)
https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#method-9-run-as-a-bitbucket-pipeline

**GitHub token is required when using user deployment.**

```
+ docker run -e OPENAI_API_KEY=$OPENAI_API_KEY -e BITBUCKET_BEARER_TOKEN=$BITBUCKET_BEARER_TOKEN -e BITBUCKET_PR_ID=$BITBUCKET_PR_ID -e BITBUCKET_REPO_SLUG=$BITBUCKET_REPO_SLUG -e BITBUCKET_WORKSPACE=$BITBUCKET_WORKSPACE bitbucket_runner:latest

An error occurred: GitHub token is required when using user deployment. See: https://github.com/Codium-ai/pr-agent#method-2-run-from-source
```

**Comment by SergioSuarezDev** [comment]
Could be related with this?
https://github.com/Codium-ai/pr-agent/issues/334

**Comment by okotek** [comment]
Hi @SergioSuarezDev 
I modified the instructions and removed redundant code here https://github.com/Codium-ai/pr-agent/pull/386
You can check the instructions in that PR to update your pipeline, it should only use the default codiumai/pr-agent:latest docker image. We'll merge this soon.
I verified that it works, please try and update here

**Comment by SergioSuarezDev** [comment]
Its seems now works but i have now a different error

```
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
ERROR:root:Failed to review PR: You exceeded your current quota, please check your plan and billing details.
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
```

**Comment by SergioSuarezDev** [comment]
I can confirm that it works!
But I can't write commands in Bitbucket, I think it works differently than github

**Comment by praveenpnj94** [comment]
Shows PR analysis. But unlike github , no other options are present such as /review and /describe.

**Comment by praveenpnj94** [comment]
This doesn't show file by file review of the PR.

**Comment by okotek** [comment]
You're right, the pipeline example in the documentation is only triggered on PR open. To handle comments in BitBucket pipelines we'd need to write a handler function and call it when the event is triggered. We'd appreciate community contribution on this.
