### ISSUE TITLE
Bitbucket Data Center going to get some love?

### ISSUE THREAD

**Issue by voarsh2** [Codium-ai/pr-agent#392]
Checked the install docs quickly, saw GitHub/GitLab and Bitbucket, but I'm going to assume that running as a Docker image to connect to a Data Center version of Bitbucket isn't going to work?

**Comment by mrT23** [comment]
@voarsh2 you are more than welcome to open a PR and show some love for Bitbucket data center.
We will integrate it

**Comment by mrT23** [comment]
@voarsh2 
see https://github.com/Codium-ai/pr-agent/pull/455
welcome to test and give feedback
