### ISSUE TITLE
Enhancement: GitHub Enterprise Compatibility for PR-Agent

### ISSUE THREAD

**Issue by liming922** [Codium-ai/pr-agent#395]
GitHub Enterprise is a self-hosting server with an API endpoint that differs from the default "api.github.com." As a result, PR-Agent currently lacks compatibility with GitHub Enterprise instances. To address this issue, a workaround on my local, involving a code change that add the base_url parameter when initializing the GitHub client.

The specific code change is in this [link](https://github.com/Codium-ai/pr-agent/blob/b6cabda5867c5ad142d2afd89bc8211e1aafcbee/pr_agent/git_providers/github_provider.py#L363):

```python
return Github(base_url='https://my.foo.github/api/v3', auth=Auth.Token(token))
```

However, to enhance the usability, it would be better to allow the base_url to be configured via the `settings.configuration.toml` file, allowing users to specify their GitHub Enterprise API endpoint.

Thanks.

**Comment by mrT23** [comment]
@liming922 
can you open a PR implementing this ?

**Comment by okotek** [comment]
Fixed here https://github.com/Codium-ai/pr-agent/pull/467 @liming922
