### ISSUE TITLE
Several types of commands on pull request not available on BitBucket 

### ISSUE THREAD

**Issue by lhtvineettiwari** [Codium-ai/pr-agent#399]
### Commands on pull request not available on BitBucket 
‣ Auto Description ([/describe](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md)): Automatically generating PR description - title, type, summary, code walkthrough and labels.
‣ Auto Review ([/review](https://github.com/Codium-ai/pr-agent/blob/main/docs/REVIEW.md)): Adjustable feedback about the PR main theme, type, relevant tests, security issues, score, and various suggestions for the PR content.
‣ Question Answering ([/ask ...](https://github.com/Codium-ai/pr-agent/blob/main/docs/ASK.md)): Answering free-text questions about the PR.
‣ Code Suggestions ([/improve](https://github.com/Codium-ai/pr-agent/blob/main/docs/IMPROVE.md)): Committable code suggestions for improving the PR.
‣ Update Changelog ([/update_changelog](https://github.com/Codium-ai/pr-agent/blob/main/docs/UPDATE_CHANGELOG.md)): Automatically updating the CHANGELOG.md file with the PR changes.
‣ Find similar issue ([/similar_issue](https://github.com/Codium-ai/pr-agent/blob/main/docs/SIMILAR_ISSUE.md)): Automatically retrieves and presents similar issues
‣ Add Documentation ([/add_docs](https://github.com/Codium-ai/pr-agent/blob/main/docs/ADD_DOCUMENTATION.md)): Automatically adds documentation to un-documented functions/classes in the PR.

**Comment by mrT23** [comment]
what ?

Read thoroughly the documentation, and share a far more detailed feedback

https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#use-docker-image-no-installation-required
https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#use-docker-image-no-installation-required
