### ISSUE TITLE
Getting exception while running with docker on local for bitbuket

### ISSUE THREAD

**Issue by praveenpnj94** [Codium-ai/pr-agent#401]
I followed the following link 

https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#use-docker-image-no-installation-required

and got the below error. Is there something wrong?

`INFO:root:Reviewing PR: https://bitbucket.org/whizdm/test-repo-pr/pull-requests/5 ...
INFO:root:Getting PR diff...
INFO:root:Getting AI prediction...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 241, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider)
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 1188, in get_llm_provider
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 1185, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/algo/ai_handler.py", line 95, in chat_completion
    response = await acompleti`

**Comment by mrT23** [comment]
The line:
`docker run --rm -it -e CONFIG.GIT_PROVIDER=bitbucket -e OPENAI.KEY=$OPENAI_API_KEY -e BITBUCKET.BEARER_TOKEN=$BITBUCKET_BEARER_TOKEN codiumai/pr-agent:latest --pr_url=<pr_url> review`
works. I validated.

Triple and quadruple checks for your errors when copying and using this **exact** line.
(i think you do have errors. what is "model='huggingface/gpt-4'" ?? there is no such thing. GPT4 requires openai account )

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/4e6dd4cf-9705-426f-afe6-0da4824e324f)

**Comment by praveenpnj94** [comment]
@mrT23 Checked this already. STill, the issue. The same open ai key and bitbucket bearer token is getting used in my personal bitbucket account to generate the review by adding in bitbucket pipeline but when I run this from my terminal, I see this issue.

I am trying different options since in bitbucket of my organisation, there is the error happening. I am not aware that which IP do I need to give to my workspace admin to whitelist. In the meantime, I thought to run it on docker on local.

<img width="968" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/13162677/61fbfcbe-5845-493f-b608-c66840ea3da0">


I even tried with run from source by following this https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#run-from-source

But getting this issue and no luck

<img width="1062" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/13162677/6614ace2-b113-4fc8-84a4-492f82761ffa">

**Comment by mrT23** [comment]
@praveenpnj94 this will be the last time I comment here.

The problem is yours. pr-agent works well with bitbucket.
i cant debug your computer and your environment.

that last run is clearly wrong, as you are running **github**. you should have found that yourself. set the correct keys.
You need to exercise judgment and reasonable knowledge.

The docker run seems valid. try to see if your key gives you full access to the repo, as the instructions clearly say

all the best
