### ISSUE TITLE
Getting "POST / HTTP/1.1" 405 Method Not Allowed with Github App

### ISSUE THREAD

**Issue by flavienmerlin** [Codium-ai/pr-agent#456]
Hi,  have deployed codium agent using a github app using this  [guide](https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#run-as-a-github-app)

Branch used: main
I am getting this errror:
"POST / HTTP/1.1" 405 Method Not Allowed in the pod logs

Please help me in resolving this issue Thanks.

**Comment by dima-horror** [comment]
@flavienmerlin , have you found a solution? I have the same error, but for gitlab integration.
