### ISSUE TITLE
VertexAI doesn't work

### ISSUE THREAD

**Issue by saorio** [Codium-ai/pr-agent#457]
I set the below configuration and added the GCP role in an instance. However, it requires OPENAPI KEY. 

```
docker run --rm -it -e VERTEXAI.VERTEX_PROJECT='project' -e VERTEXAI.VERTEX_LOCATION='asia-northeast1' -e GITHUB.USER_TOKEN=[Token] codiumai/pr-agent:latest --pr_url [PR URL] review -config_path=/path/to/configuration.toml
```
```
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

```configuration.toml
[config]
model = "vertex_ai/codechat-bison"
litellm.set_verbose=True
```

After I set OPENAPI KEY, it worked. It answered OPENAPI.
Could you enhance this or point out my configuration?

**Comment by mrT23** [comment]
@saorio
see https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#vertex-ai
you need to define a vertex model, instead of the default openai

-e config.model='vertex_ai/codechat-bison' -e config.fallback_models='vertex_ai/codechat-bison'

**Comment by saorio** [comment]
@mrT23 Thank you, it worked.

**Comment by alessio-locatelli** [comment]
> `-config_path=/path/to/configuration.toml`

By the way, that is a very misleading documentation. That is **not** a path to the the file. That is for overriding specific parameters, e.g. `-config_path=pr_reviewer__require_tests_review=true` (not tested).

Just wasted some time trying to debug why `-config_path=/path/to/configuration.toml` is not working.
