### ISSUE TITLE
Add Amazon Bedrock support

### ISSUE THREAD

**Issue by tmokmss** [Codium-ai/pr-agent#459]
Hi, thank you for developing this great tool!

I'm asking if it is possible to add Amazon Bedrock support to `pr-agent` (just out of personal interest). Amazon Bedrock is a fully managed service that offers a choice of high-performing foundation models such as Claude, Cohere, etc, that runs on AWS. Since `litellm` already [supports Bedrock](https://docs.litellm.ai/docs/providers/bedrock), I believe we can add the support with a little change.

If it's acceptable, I'm willing to submit a PR. Thanks!

**Comment by mrT23** [comment]
a PR will be welcome, i think it should be similar to other platforms we support, like [VertexAI](https://github.com/Codium-ai/pr-agent/pull/436)

**Comment by tmokmss** [comment]
Cool, thanks! I'll work on this later  :)

**Comment by mrT23** [comment]
@tmokmss 
is this still an open task you are working on, or should I close the issue ?
