### ISSUE TITLE
Timeout when the extension is trying to log in.

### ISSUE THREAD

**Issue by opus-x** [Codium-ai/pr-agent#468]
Currently, I am unable to use the Codium AI extension due to my computer’s slow performance. I have encountered an error message that reads '`Codium login failed: ‘AxiosError: timeout of 8000ms exceeded`’, which requires me to log in again every time I encounter it. I hope that the timeout issue will be resolved soon. I also attempted to delete my account to sign up through Github, but the extension is not allowing me to do so, as it is detecting a difference in the sign-in method compared to the sign-up method. I suspect that my account was not deleted.

**Comment by mrT23** [comment]
This is pr-agent repo.
open this issue here:
https://github.com/Codium-ai/codiumai-vscode-release
