### ISSUE TITLE
Does the code get sent to the backend?

### ISSUE THREAD

**Issue by seiyeah78** [Codium-ai/pr-agent#474]
I'm trying to set up pr-agent using the provided GitHub Actions. The [Data Privacy](https://github.com/Codium-ai/pr-agent#data-privacy) section in the README states that it only interacts with OpenAI.

However, in the [Data Gathering and Data Flow](https://www.codium.ai/blog/codiumai-security-our-commitment-to-data-privacy-and-security/) blog post, it mentions that when using CodiumAI PR-Agent, data is sent to CodiumAI's backend.

In this case, does it mean that when using pr-agent with GitHub Actions, the code will be sent to CodiumAI?

**Comment by mrT23** [comment]
Your code in PR-Agent GitHub Actions is not sent to the CodiumAI. 
It's between you and your LLM provider (OpenAI, or any other provider you choose. You can use a self-hosted LLM, for example, for maximal privacy)

The blog discusses CodiumAI IDE plugins. We will fix the wrong line regarding PR-Agent

**Comment by seiyeah78** [comment]
@mrT23 
Thank you for your reply. 
I understood. I'll try using it right away.
