### ISSUE TITLE
Gitlab Job

### ISSUE THREAD

**Issue by PaulWoitaschek** [Codium-ai/pr-agent#482]
I'd like to use the pr-agent without hosting any infrastructure.

If I understand correctly, the github action does exactly this: As part of an action, run a one shot review.
It would be great the same would work for gitlab as well so that one could specify it as part of a job.

**Comment by mrT23** [comment]
Hi @PaulWoitaschek 

We havn't implemented yet in GitLab an equivalent to GitHub action, although it is probably possible.

We do have a (paid) hosted GitLab webhook, where we take care of everything (including the LLM provider). If you are interested in it, contact [support@codium.ai](mailto:support@codium.ai) or visit [CodiumAI pricing page](https://www.codium.ai/pricing/)
