### ISSUE TITLE
The ability to use pr-agent on Github action using azure open ai

### ISSUE THREAD

**Issue by veronicavero** [Codium-ai/pr-agent#494]
Please enhance the env configuration to use azure open ai, also please share an example to do so. 
Thanks

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#azure

**Comment by veronicavero** [comment]
@mrT23 I have read the doc, but it said ".screte.toml" that is for python to execute or i execute from source code?
I want to use the Github action, which will be the "pr_agent.yaml" for the action. How it can be set there? 
just put the same information as ".screte.toml" on the "pr_agent.yaml" under evn?

**Comment by mrT23** [comment]
@veronicavero 
If you want to use GitHub action, first read the relevant section of github action, in the same page.
It answers all the questions you raised.
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/2243753c-356c-4ea1-b10f-f3f87153087f)


All the best
