### ISSUE TITLE
GitHub action fails coz OpenAI API Key's Key was changed(probably)

### ISSUE THREAD

**Issue by alik-eth** [Codium-ai/pr-agent#527]
I get this error when I run pr agent as a GH Action:
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

**Comment by alik-eth** [comment]
I have had the PR agent working and today I discovered this regression.

**Comment by mrT23** [comment]
thanks for the feedback. looking into this

**Comment by mrT23** [comment]
(p.s - you can work against a stable docker, like v0.11, to avoid this)
