### ISSUE TITLE
Allow Running PR-Agent with Local Models running on Ollama

### ISSUE THREAD

**Issue by skitiz** [Codium-ai/pr-agent#535]
I was wondering if we could have the ability to run PR-Agent locally with an Ollama model instead of using an OpenAI key.

**Comment by mrT23** [comment]
yes

https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#huggingface

**Comment by mrT23** [comment]
Although, personally i think there are better models for code than Ollama 😉

**Comment by Sammindinventory** [comment]
@mrT23  how do i use it and where do i make changes?

**Comment by mrT23** [comment]
Use who ?

**Comment by Sammindinventory** [comment]
local llm or run PR-Agent locally with an Ollama model

**Comment by mrT23** [comment]
How to setup a local model is out-of-scope for pr-agent.
there are guides online (TGI)

**Comment by skitiz** [comment]
Thank you so much!

**Comment by fredrikburmester** [comment]
Could we re-open this issue? I can't find any documentation on how to use locally run models with something like Ollama or LMStudio. @mrT23

**Comment by mrT23** [comment]
@fredrikburmester 
are you sure you looked for documentation ?

![image](https://github.com/user-attachments/assets/fd6d23f4-25da-4321-9a6c-c5f0c59cea47)
https://pr-agent-docs.codium.ai/usage-guide/additional_configurations/#hugging-face

If you think something is missing, open a PR with updated documentation
