### ISSUE TITLE
No response on some commands from @CodiumAI-Agent

### ISSUE THREAD

**Issue by pfilaretov42** [Codium-ai/pr-agent#553]
Hi,

I'm running pr-agent on my public GitHub repository with [CodiumAI-Agent](https://github.com/CodiumAI-Agent). I'm adding comments to PRs to run it, however, not every command produces response comments in the PR. For instance, the following commands did not take effect, except eyes emoji reaction 👀:
```
@CodiumAI-Agent /describe
@CodiumAI-Agent /generate_labels
@CodiumAI-Agent /analyze
```

I guess it may happen for different reasons, e.g.
- unsupported programming language, e.g., Kotlin for `/analyze` command
- lack of permissions to modify PR
- etc

So, I have two points here:
1. Could you please advise how to solve issues with the mentioned commands not working?
2. Even if it is expected that some command is not working, it would be great to have some feedback from the pr-agent in comments saying that something is not supported, something went wrong, etc.

Sample PR: https://github.com/pfilaretov42/advent-of-code/pull/1

Thanks,
Petr

**Comment by mrT23** [comment]
Hi @pfilaretov42 

- You are using a "promotional" bot of PR-Agent, which doesn't have access to edit existing data in your PR.
Hence, /describe and /generate_labels won't work for you.
If you just want to see a how a possible output will look like, you can do:
"@CodiumAI-Agent /describe --pr_description.publish_description_as_comment=true"

https://github.com/pfilaretov42/advent-of-code/pull/1#issuecomment-1870535136

- "Analyze" is part of PR-Agent-Pro, and not the base open-source
https://www.codium.ai/pricing/

- in any case, the promotional bot is not for lasting usage, and will probably be taken down in the near future. 
 If you think PR-Agent is useful for you, either sign up to codium, or self-host you own agent:
https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md
When you use a proper agent, /describe and /generte_labels will work for you.
