### ISSUE TITLE
CLI add_docs does not post collapsible

### ISSUE THREAD

**Issue by EduardDurech** [Codium-ai/pr-agent#591]
` py -m pr_agent.cli --pr_url=<repo url> add_docs` does not post a collapsible list as when calling `/add_docs` on the repo. `describe` has a config flag for this, and `analyze` cannot be tested as it's not in the CLI

<details><summary>CLI</summary>
<p>

<img src=https://github.com/Codium-ai/pr-agent/assets/39579228/4bbed311-497e-4524-878e-1ff706f7020d, width='600'>

</p>
</details>

<details><summary>GitHub</summary>
<p>

<img src=https://github.com/Codium-ai/pr-agent/assets/39579228/d847ea98-f5ef-4b31-a379-7a81aadb1624, width='600'>

</p>
</details>

**Comment by mrT23** [comment]
There is a difference in the feature between 'PRO' and regular version of PR-Agent.

When you work from CLI, you are using the regular version, not the PRO

**Comment by EduardDurech** [comment]
> There is a difference in the feature between 'PRO 💎 ' and regular version of PR-Agent.
> 
> When you work from CLI, you are using the regular version, not the PRO.
> 
> As you can see, the PRO feature is much better (it identifies all the components that changed, not just new ones)

Makes sense, feel free to close then, is there a plan maybe to support CLI-PRO 💎? That would recognize your status based on Codium Git integration

**Comment by mrT23** [comment]
The PRO is closed source, so unfortunately we can't share a CLI version of it
