### ISSUE TITLE
CLI Fails if comment not in hunk/diff

### ISSUE THREAD

**Issue by EduardDurech** [Codium-ai/pr-agent#592]
CLI `github_provider` `publish_code_suggestions` returns Error 422
`{"message": "Unprocessable Entity", "errors": ["Pull request review thread line must be part of the diff and Pull request review thread diff hunk can't be blank"], "documentation_url": "https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request"}`

at https://github.com/Codium-ai/pr-agent/blob/e7251ada3f8441b032d6bdd402c02522436ad138/pr_agent/git_providers/github_provider.py#L269

Checking https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#create-a-review-for-a-pull-request for `comment` only `'path'` and `'body'` are required; however, my `post_parameters_list` contains both:

`[{'body': '**Suggestion:** Proposed documentation\n```suggestion\n"""\n fooText\n```', 'path': 'foo/bar.ts', 'line': 108, 'side': 'RIGHT'}]`

It is likely because the comment is masked in @@, i.e. not in diff hunk, as per the documentation

> The position value equals the number of lines down from the first "@@" hunk header in the file you want to add a comment. The line just below the "@@" line is position 1, the next line is position 2, and so on. The position in the diff continues to increase through lines of whitespace and additional hunks until the beginning of a new file.

Although this is for `position` and not `line`, it seems that in any case comment not in diff hunk return this error:
https://github.com/mitchspano/sfdx-scan-pull-request/issues/16
related issue:
https://github.com/orgs/community/discussions/59057

This is related to https://github.com/Codium-ai/pr-agent/issues/221 but this is for a request of one function and is about 5 lines of comments, the problem is not a big request but that the line is not part of the diff hunk, it is masked in @@

I confirmed this by setting `line` to a line number in the diff hunk (in my case 111, instead of 108) and it posts

I think this is a limitation of the Rest API and either need to open an issue with Git to support it or force a commit to change the line so it becomes hunked

**Comment by EduardDurech** [comment]
Would be a shame not to have out-of-hunk review so a work-around would be good, also to support out-of-pr files so one day can do a repo or reference search

**Comment by mrT23** [comment]
Hi @EduardDurech 

- When working with LLMs, there will not be 100% success. Never. the model can make mistakes. take that into account
- It is annoying that GitHub API does not enable to give comments outside +-3 lines of a changed line. In the GUI, you can.
- When a specific message fails, we still publish the others. So its not a complete failure. You will see some code suggestions.
- Take a look at this:
https://github.com/Codium-ai/pr-agent/pull/576#issuecomment-1881435862
I think it can mitigate the issue (although not fully solve it)

**Comment by EduardDurech** [comment]
> Hi @EduardDurech
> 
>     * When working with LLMs, there will not be 100% success. Never. the model can make mistakes. take that into account. We ask the model to address only new code (+ lines), but sometimes it's not the case.
> 
>     * It is annoying that GitHub API does not enable to give comments outside +-3 lines of a changed line. Even in the GUI, you can extend the view, but not send comments there.
> 
>     * When a specific message fails, we still publish the others. So its not a complete failure. You will still see some code suggestions.
> 
>     * Take a look at this:
>       [Less noisy fallback for `publish_code_suggestions` in case of invalid comments #576 (comment)](https://github.com/Codium-ai/pr-agent/pull/576#issuecomment-1881435862)
>       I think it can mitigate the issue (although not fully solve it)

Yes, it is actually a cool "feature" that it would do it outside the diffs, as it would cover the parent function, but this is a limit of Git Rest, I thought maybe there are some hacky ways to do it like forcing a commit on the out-of-hunk-scope line just so it shows in PR diff, or as you mentioned having it in-line (this kind of goes back to the issue #591 thought that it's not posted on CLI to inline), would have to append `body='fooText', event='COMMENT'` to the `create_review`, I kind of already implemented this locally to keep the functionality as I find it useful it actually works out of scope

**Comment by mrT23** [comment]
@EduardDurech we merged https://github.com/Codium-ai/pr-agent/pull/594, and also added significant improvements to the 'summarize' mode.

you are welcome to share feedback if you encounter issue with any of the new modes
