### ISSUE TITLE
Integration with Azure Devop

### ISSUE THREAD

**Issue by jaytonic** [Codium-ai/pr-agent#610]
We are currently using Azure Devop for our git hosting and pull-request process.
Is there some plan to integrate with it?

**Comment by SagiMedina** [comment]
@jaytonic the azure devops provider was recently updated. take a look here:
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent%2Fgit_providers%2Fazuredevops_provider.py

There is still some work to do, but you can start by running it with cli commands

**Comment by jaytonic** [comment]
> @jaytonic the azure devops provider was recently updated. take a look here: https://github.com/Codium-ai/pr-agent/blob/main/pr_agent%2Fgit_providers%2Fazuredevops_provider.py
> 
> There is still some work to do, but you can start by running it with cli commands

That's awesome, is there some instructions on how to setup it somewhere?

**Comment by SagiMedina** [comment]
Sure, take a look at the CLI section, if it is still not clear, write here and tag me.

**Comment by mrT23** [comment]
@jaytonic 
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#azure-devops-provider

**Comment by SagiMedina** [comment]
Regarding the configuration, nothing changed.

**Comment by benjaminbluhm** [comment]
Hi @SagiMedina I am also interested in the Azure DevOps Repo integration.

Is my understanding correct that currently only "local" mode is supported? 

And do you have roadmap when "online" mode (commenting on PRs etc.) will be supported?

**Comment by mrT23** [comment]
@benjaminbluhm 
contribution from the community will be welcomed for supporting "online" mode, something similar to
`pr_agent/servers/github_app.py`

**Comment by benjaminbluhm** [comment]
@mrT23 Thanks for you message, actually would love to do it, but unfortunately no capacity to contribute at the moment

**Comment by mrT23** [comment]
ok
