### ISSUE TITLE
Feature: allow hiding the buttons displayed before each function

### ISSUE THREAD

**Issue by felix021** [Codium-ai/pr-agent#611]
Firstly thanks for your wonderful work.

And I'm a bit troubled by theses buttons:

![image](https://github.com/Codium-ai/pr-agent/assets/367085/0b0982ea-a305-444a-9f21-c7beb4d0154b)

They are too easy to be clicked unexpectedly and trigger a popup window from the sidebar.

I'm actually not using these functions, so could you add an option to hide them or put it in the floating tips only when the mouse hangs over?

**Comment by mrT23** [comment]
This is not codeium
