### ISSUE TITLE
Provide code suggestions up-front

### ISSUE THREAD

**Issue by bluepnume** [Codium-ai/pr-agent#625]
Hi all!

Here is my config:

```
[pr_reviewer]
inline_code_comments = true
[pr_code_suggestions]
summarize = false
auto_extended_mode = true
[github_app]
pr_commands = [
    "/describe",
    "/review",
    "/improve"
]
handle_push_trigger = true
```

The problem I'm having is:

- When I first push the PR, I get inline comments, but they don't contain code suggestions
- When I reply `/improve`, then I get code suggestions (with a 'commit suggestion' button) in the comments

How can I get the code suggestions by default? I thought having `/improve` in the pr_commands would do it but doesn't seem to help.

**Comment by bluepnume** [comment]
![](https://files.slack.com/files-pri/T03FHMANKE2-F06FBK6NF0W/screenshot_2024-01-24_at_10.49.16___pm.png)

![](https://files.slack.com/files-pri/T03FHMANKE2-F06FXFFF9A5/screenshot_2024-01-25_at_1.05.10___am.png)

**Comment by bluepnume** [comment]
![Screenshot 2024-01-25 at 1 05 10 AM](https://github.com/Codium-ai/pr-agent/assets/1219075/38cb11d6-861b-4a41-9807-bb424f3ea850)
![Screenshot 2024-01-24 at 10 49 16 PM](https://github.com/Codium-ai/pr-agent/assets/1219075/3fd7b78d-5a43-4f8f-90b6-2b7c95f53e90)

**Comment by mrT23** [comment]
you are confusing **GitHub app** with **Github action**.

**Github action** have different configurations
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-action

**Comment by mrT23** [comment]
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/c7440d0a-1067-4f6e-b367-75c649f75d55)
not for github action

**Comment by bluepnume** [comment]
Thanks @mrT23 -- but still the same problem, we're not getting those improve code suggestions

```
[pr_reviewer]
inline_code_comments = true
[pr_code_suggestions]
summarize = false
auto_extended_mode = true
[github_action]
pr_commands = [
    "/describe",
    "/review",
    "/improve"
]
handle_push_trigger = true
```

<img width="851" alt="Screenshot 2024-01-26 at 1 05 10 PM" src="https://github.com/Codium-ai/pr-agent/assets/1219075/09a2ef0d-1237-4f62-87ab-9c572b715b5b">

**Comment by mrT23** [comment]
You are using configurations that don't exist.

Instead, follow the readme:
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-action

**Comment by bluepnume** [comment]
Apologies, tried to take a short cut there.

That said, I'm now using:

```
[pr_reviewer]
inline_code_comments = true
[pr_code_suggestions]
summarize = false
auto_extended_mode = true
[pr_description]
publish_description_as_comment = false
add_original_user_description = true
[github_action_config]
auto_review = true
auto_describe = true
auto_improve = true
```

And `auto_improve` is still only adding comments, not code suggestions like the `/improve` command.

Is there any way to achieve what I want to do with a github action, or do I need to switch to a github app?

**Comment by bluepnume** [comment]
Nevermind, works now! Looks like it took another few seconds to add the code suggestions. Thank you so much for all the help!
