### ISSUE TITLE
Overwriting problem of GITHUB_ACTION.* Environment Variables by GITHUB_ACTION in GitHub Actions

### ISSUE THREAD

**Issue by ainoya** [Codium-ai/pr-agent#626]
I have encountered an issue where the environment variables prefixed with `GITHUB_ACTION.*` are being overwritten by the `GITHUB_ACTION` variable during the execution of GitHub Actions.

When GitHub Actions executes a `docker run` command, the default environment variable `GITHUB_ACTION` provided by GitHub is appended later, leading to the overwriting of the following environment variables referenced by pr-agent:

- `GITHUB_ACTION.AUTO_IMPROVE`
- `GITHUB_ACTION.AUTO_DESCRIBE`
- `GITHUB_ACTION.AUTO_REVIEW`

This issue occurs because of how `docker run` is executed within GitHub Actions, with arguments like the following:

```
/usr/bin/docker run --name d511c98b2fb6ebf644398423fc5cde347b10_f592f2 --label 60d511 --workdir /github/workspace --rm -e "OPENAI_KEY" -e "GITHUB_TOKEN" -e "PR_REVIEWER.EXTRA_INSTRUCTIONS" \
-e "PR_REVIEWER.ENABLE_REVIEW_LABELS_EFFORT" -e "PR_DESCRIPTION.EXTRA_INSTRUCTIONS" -e "PR_CODE_SUGGESTIONS.SUMMARIZE" \
-e "GITHUB_ACTION.AUTO_REVIEW" -e "GITHUB_ACTION.AUTO_IMPROVE" -e "GITHUB_ACTION.AUTO_DESCRIBE"\
 ...  -e "GITHUB_ACTION"  ...
```

Reference to GitHub's default environment variables: [GitHub Docs - Default Environment Variables](https://docs.github.com/ja/actions/learn-github-actions/variables#default-environment-variables)

For example, if a job step specifies `id: pr-agent`, it results in `GITHUB_ACTION=pr-agent`. This causes the pr-agent to throw the following error:

```
> File "/app/pr_agent/git_providers/utils.py", line 29, in apply_repo_settings
    section_dict[key] = value
    │            │      └ True
    │            └ 'auto_review'
    └ 'pr-agent'
```

Is there a way to avoid this issue? If not, would it be advisable to change the pr-agent's configuration key name from `[github_action]` to something that does not overlap with GitHub's default `GITHUB_ACTION` variable, such as `[github_action_config]`?

**Comment by mrT23** [comment]
just so i make sure i understand:

You are saying that "GITHUB_ACTION" is kind of a reserved keyword, we shouldn't override ?

**Comment by ainoya** [comment]
Yes, that’s correct.

**Comment by mrT23** [comment]
done
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-action
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/servers/github_action_runner.py#L88

share feedback if you encounter problems

**Comment by ainoya** [comment]
Everything is working perfectly now. Thank you so much for your assistance!
