### ISSUE TITLE
Google Secret Provider must be specified in config

### ISSUE THREAD

**Issue by amahpour** [Codium-ai/pr-agent#633]
### Problem
Based on [this code](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/secret_providers/__init__.py#L14) the `config.secret_provider` cannot be left as an empty string.

### Workaround
To skirt around this issue, one can comment out `config.secret_provider` in `pr_agent/settings/configuration.toml`. This is a non-optimal solution as it shows up in the `git diff`.

### Suggested Fix
Allow for an empty string to be passed into the `config.secret_provider` field (via environment variable or `.secrets.toml`) or remove raised exception check completely.

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/pull/634 should solve this

**Comment by mrT23** [comment]
done
