### ISSUE TITLE
Question: personal access token types

### ISSUE THREAD

**Issue by idubnori** [Codium-ai/pr-agent#645]
Can use GitHub `Fine-grained` personal access token has set appropriate permissions,  instead of `classic` type?

Ref.
> A GitHub\GitLab\BitBucket personal access token (classic), with the repo scope. [GitHub from [here](https://github.com/settings/tokens)]
> https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#run-as-a-github-action

**Comment by mrT23** [comment]
i think that yes. just try
