### ISSUE TITLE
Why is the action limited to `pull_request: [opened, reopened]`?

### ISSUE THREAD

**Issue by rajyan** [Codium-ai/pr-agent#648]
Currently the Codium-ai/pr-agent Github Action runs pr-agent on `pull_request: [opened, reopened]`

https://github.com/Codium-ai/pr-agent/blob/e4f177908b620e46740b03966fda9243473d979e/pr_agent/servers/github_action_runner.py#L82

I think it is a sensible default (running pr-agent in 'synchronize' would get flooded), but there are lot of use cases that are reasonable to run pr-agent in 'synchronize' or 'ready_for_review'.

For example

* Run when 'ready_for_review' for draft pull requests instead of `opened`, because in most cases /review, /describe or /improve for draft pull requests are useless
* Run pr-agent on 'synchronize' when labeled with a specific label

Simply put, we want to have control over when the PR agent runs according to our own conditions.

Is it possible to change this line into a config? or are there any reasons that the event is restricted to `[opened, reopened]`?

**Comment by mrT23** [comment]
Github action is a limited feature. 

if you want full control, use PR-Agent Pro 💎  app, where you can modify everything (for example, running on push events: https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools-for-push-actions-commits-to-an-open-pr )

I won't enable running pr-agent github action on 'synchronize' for two reasons:
-too intrusive and wastefull for most people
-every time you run github action, you pull a docker. this operation cost us money, and with large numbers, its not a negligible amount. 'synchronize' will force us to use far more expensive solutions

you can open a PR for adding 'ready_for_review'. it is reasonable.
But PR-Agent Pro 💎 will give you the full control you want, as well as many other advantages

**Comment by rajyan** [comment]
@mrT23 

Thank you for your explanation.

> -too intrusive and wasteful for most people

I totally agree with your point.

https://github.com/Codium-ai/pr-agent/blob/e4f177908b620e46740b03966fda9243473d979e/pr_agent/servers/github_action_runner.py#L82
I was wondering if this line line could be configured as a config (with default as the current `["opened", "reopened"]`)

> -every time you run GitHub action, you pull a docker. This operation costs us money

I couldn't get your point for this part. Running GitHub Actions builds from `Dockerfile.github_action_dockerhub` as configured here https://github.com/Codium-ai/pr-agent/blob/79dac3f419f11c6c9e7dcc2410418b6d0473b269/action.yaml , so I believe it wouldn't affect your cost.

> You can open a PR for adding 'ready_for_review'. It is reasonable.

I'll open it soon.

> But PR-Agent Pro 💎 will give you the full control you want, as well as many other advantages.

Thanks for your advice!
We are interested in GitHub App too, but can it do same things that GitHub Actions can do?

If we use GitHub Actions we can combined the pr-agent action with other actions. For example, we can run https://github.com/dorny/paths-filter in a previous step, and only run the review if specific set of files were changed.

**Comment by mrT23** [comment]
Every time you run pr-agent as a GitHub action, you pull our docker from dockerhub.
This creates a lot of traffic for our dockerhub account.
'synchronize' can increase the traffic by ~x10 - hence no.

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/2a2f54b1-4ede-4af2-85ab-dad3b0ec0f3e)

**Comment by rajyan** [comment]
@mrT23 

Thanks you for you explanation!
