### ISSUE TITLE
[feature request] new command `/todo` that opens an issue with details

### ISSUE THREAD

**Issue by coditamar** [Codium-ai/pr-agent#662]
when a developer calls the `/todo` inside the Conversation or Files, 
then a new issue is opened with the todo details along with link to the location of the relevant comment and PR.
issue can is configurable if to be opened as GitHub issue or JIRA ticket.

**Comment by mrT23** [comment]
isn't it very similar to this:
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-comment
?
