### ISSUE TITLE
Not working with GitHub enterprise?

### ISSUE THREAD

**Issue by Freepaq** [Codium-ai/pr-agent#724]
Hello 

Our enterprise have an address like xxxxx.githib.xx

With GitHub actions, we have an error saying that the URL git is not valid
Is that possible to fix that ?

**Comment by Freepaq** [comment]
It's xxxxx.github.xx not xxxxx.githib.xx sorry

**Comment by mrT23** [comment]
PR-Agent PRO supports GitHub enterprise.

For self-host github action, try and see, I am not sure
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L126
