### ISSUE TITLE
Feature Request - Support Claude3 model via Amazon Bedrock

### ISSUE THREAD

**Issue by FaranIdo** [Codium-ai/pr-agent#742]
Add support for Claude3 model via Amazon Bedrock.

LiteLLM library already supports it https://github.com/BerriAI/litellm/releases/tag/v1.29.1.

I tried to add it by myself, but the current PR agent repo dependencies on old version of LiteLLM, and it wasn't trivial to update it due to some conflicts with openai library.

**Comment by mrT23** [comment]
So adding it is equal to upgrading litellm and solving the dependencies?

**Comment by mrT23** [comment]
This PR will enable claude3:
https://github.com/Codium-ai/pr-agent/pull/746

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/f03ff494-b455-43d4-bc4f-f176eb3d1b06)

**Comment by FaranIdo** [comment]
Hi @mrT23 , thanks for the quick response.
I tested your branch, and it seems it tries to use the Anthropic direct API.
Actually, I wanted to use it via Amazon Bedrock.

Once I adds `anthropic.claude-3-sonnet-20240229` to __init__.py file of the algo folder, I got the following exception:
![image](https://github.com/Codium-ai/pr-agent/assets/22587682/0c952150-0193-4daf-a071-cf2e89135749)

**Comment by mrT23** [comment]
i don't have access to amazon bedrock, so i cant debug it

read
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#amazon-bedrock
and try to understand what's missing, probably a line or two somewhere

**Comment by FaranIdo** [comment]
I will try figuring it out. 
By the way, currently, using in the config `anthropic.claude-v2` leads to bedrock usage, while `claude-2` uses directly the API of Anthropic, which is kind of confusing. 
You can think about a more effortless user experience for choosing the correct model via Bedrock.

**Comment by mrT23** [comment]
This is a clear case where the community should contribute (a.k.a you)
all the best
