### ISSUE TITLE
[GitHub Release] Could you create a new release from latest develop branch.

### ISSUE THREAD

**Issue by psbss** [Codium-ai/pr-agent#749]
Hi, Thank you so much for your development of PR-Agent.

We've noticed significant improvements in output recently and would like to leverage these advancements in our project.

Currently, our update process involves specifying branches, which may lead to updates with unstable versions. Stability is paramount for our team, and we prefer updating our dependencies by specifying tags for this reason.

Given this context, we have two requests:

1. Could you please release a new stable version reflecting recent improvements?
2. If possible, introducing a regular release schedule would greatly assist projects like ours in planning and integration.

Thank you all.

**Comment by mrT23** [comment]
@psbss 
regular PR-Agent will have "Stable" releases once a month. We plan to do one next week
you can choose whether to use the "Stable" version, or a nightly updated "latest" version.

if you want "stability" + "nightly updated" (along with other benefits), I recommend using PR-Agent PRO. We guarantee there both.
https://github.com/Codium-ai/pr-agent?tab=readme-ov-file#pr-agent-pro-

**Comment by psbss** [comment]
Thank you for your reply.
I will consider to use PR-Agent Pro👍
