### ISSUE TITLE
Keeping images in a git repository slows down the git clone

### ISSUE THREAD

**Issue by gorarakelyan** [Codium-ai/pr-agent#77]
Keeping images in a git repository can slow down the git clone command because it makes the repo bigger and heavier.

# Alternatives

- Use cloud storages: save images in cloud storage instead of directly in your git repo.
- Use GitHub's static files hosting

**Comment by gorarakelyan** [comment]
btw thanks for this awesome tool! 🙌

**Comment by okotek** [comment]
https://github.com/Codium-ai/pr-agent/pull/80 @almog-lv please review

**Comment by almog-lv** [comment]
@gorarakelyan thank you for your excellent suggestion, we removed the images from the repository
