### ISSUE TITLE
Feature request: More examples

### ISSUE THREAD

**Issue by calebAtIspot** [Codium-ai/pr-agent#794]
I would love to see more examples of the PR agent to see if it's worth using before I spend money on AI API usage. I see you run it on your own PR's, but I'm not familiar with the internals of your app to judge how useful the responses are. It would be nice to have simpler examples where it's easy to tell how the AI performs. 

In the spirit of this feature request, I'll share my experience with using it:

---

I tested it on a file with a simple terraform bug 30 lines long (163 tokens).

Verbosity: Overly verbose. I don't find value in the effort to review message, although it looks like I can turn that off
Usefulness: Mixed. It found a few code smells but didn't accurately identify the bug.  
Token usage: 1146 tokens usage against chatGPT4 (the default)

What's interesting is a very simple "Please review this PR" prompt along with the file pasted into openAI GPT4 chat will accurately identify the bug. I tested multiple times and it identified it every time. Still, maybe it's just very bad luck codium didn't identify it, it's hard to know with the AI randomness in output.

**Comment by calebAtIspot** [comment]
Another example:
```hcl
resource "aws_s3_bucket" "bob" {
  name = "my_bucket_123"
  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}
```

It failed to identify the bad characters in `name` (_) or the fact that `name` is not a valid attribute. Same issue with native ChatGPT4 chat and amazon Q.

timing: 41 seconds

Too bad, wish I had a passing example because I like the idea of an AI PR reviewer.

**Comment by mrT23** [comment]
- I cannot address any algorithmic issue\problem without a full reproduction code from a public repo.

- regarding "`examples of the PR agent to see if it's worth using before I spend money on AI API usage`":
I don't understand this sentence. 
  - You can use docker, CLI, GitHub action or GitHub app with your own API key, and **examine and evaluate the results on your private code**
https://pr-agent-docs.codium.ai/installation/

  - You are also entitled to two weeks of free trial usage with PR-Agent Pro, where you can also examine and evaluate the results on your private code
