### ISSUE TITLE
pr-agent module publishing to pypi

### ISSUE THREAD

**Issue by gregoryboue** [Codium-ai/pr-agent#813]
Hi, 

It would be great to publish pr-agent as pypi module on https://pypi.org/ , it it planned for the future ?

**Comment by mrT23** [comment]
thats a good idea. we will look into that
👍

**Comment by gregoryboue** [comment]
Great, thanks you !

**Comment by mrT23** [comment]
see
https://pr-agent-docs.codium.ai/installation/locally/#using-pip-package
