### ISSUE TITLE
Environment variables override

### ISSUE THREAD

**Issue by s1moe2** [Codium-ai/pr-agent#819]
I'm currently deploying the PR agent according to the docs but I would like set the secrets via environment variables instead of having them built into the Docker image.
The problem is that AWS Lambda env vars cannot have "." in the name. This means I can't create vars such as `GITHUB.WEBHOOK_SECRET`.

However, I'm not sure I'm doing this right.
I took a look at the code but I'm not that familiar with Dynaconf so I can't figure out if I need to set variables as `GITHUB.WEBHOOK_SECRET` to override the toml configuration of it's a different pattern (that eventually is accepted by Lambda).

Appreciate the help!

**Comment by mrT23** [comment]
Have you tried this:
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/1fe2d95e-f9b5-4872-848e-2e1d3672e7ce)

?

**Comment by s1moe2** [comment]
Awesome. Thanks for confirming this.

**Comment by mrT23** [comment]
it worked ? can i add it to the docs ?

**Comment by s1moe2** [comment]
@mrT23 Sorry, I was under the impression you were confirming this works.
Yes, it works
![image](https://github.com/Codium-ai/pr-agent/assets/36140182/8db7f0dc-fa52-4c8d-b44d-ace4185d00fb)
