### ISSUE TITLE
Add persistent_comment option for `/describe`

### ISSUE THREAD

**Issue by hnoson** [Codium-ai/pr-agent#835]
The comment isn't replaced and there is no option to do it when publish_description_as_comment is enabled.

**Comment by mrT23** [comment]
its possible

why do you want to use at all the mode of 'publish_description_as_comment' for describe ?

**Comment by hnoson** [comment]
since we update the description manually and it's sometimes overwritten by the generated one

**Comment by mrT23** [comment]
unclear

What's your use case for using `publish_description_as_comment` at all ? why not write directly to the PR header ?
It does not overwrite the original content, it **adds** to it:

https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened

**Comment by hnoson** [comment]
1. Open a PR
2. Start editing the description manually
3. PR-Agent generates content based on the content before editing
4. Finish editing manually
5. The manual edit or PR-Agent overwrites content of the other

To avoid this issue, we enabled `publish_description_as_comment`

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/pull/837
done

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/d0937358-8992-45c7-b609-4dba1063edb8)

**Comment by hnoson** [comment]
Thanks!
