### ISSUE TITLE
No need to check OPENAI_KEY when using non OpenAI models

### ISSUE THREAD

**Issue by nakamichiworks** [Codium-ai/pr-agent#855]
PR Agent silently fails when I use the non OpenAI models such as Bedrock in Github Actions if I do not set `OPENAI_KEY`.

This failure is caused by unnecessarily checking existence of `OPENAI_KEY` in the following code, which seems to be removed safely.

https://github.com/Codium-ai/pr-agent/blob/f0c5aec0e431461d751d802b6a7132f32c940c38/pr_agent/servers/github_action_runner.py#L50

**Comment by mrT23** [comment]
you are welcome to open to open a PR to address this
