### ISSUE TITLE
Can't log in to IntelliJ IDEA

### ISSUE THREAD

**Issue by Parkstud** [Codium-ai/pr-agent#861]
Unable to successfully log in after successfully authorizing the webpage, the status keeps loading, as if a callback was made to a port on localhost, but the port is unresponsive.

IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64

call url

https://accounts.google.com/o/oauth2/auth?client_id=252179682924-ahfq8vjkr8a08ak2310abj6j3ocgb9k2.apps.googleusercontent.com&redirect_uri=https://proxy.codium.ai/v1/auth/google-login/jetbrains/codium.codium&scope=email%20profile%20openid&response_type=code&access_type=offline&state=63342

**Comment by lyx3314844** [comment]
我也是一样，不知道该如何处理。联系开发人员很多次没有回复
