### ISSUE TITLE
Can we use pr-agent with custom llm provider?

### ISSUE THREAD

**Issue by ElonaZharri** [Codium-ai/pr-agent#868]
Is this feature available yet?

**Comment by mrT23** [comment]
yes

https://pr-agent-docs.codium.ai/usage-guide/additional_configurations/#changing-a-model

**Comment by mrT23** [comment]
In addition, in the near future, PR-Agent Pro would also offer seamless support of claude3 along with GPT-4

**Comment by ElonaZharri** [comment]
I have `llama2` running in my local, and I have made the necessary adjustments in `.secrets.toml`, `configuration.toml` and `__init__.py`, as specified here:
```
[__init__.py]
MAX_TOKENS={
    "ollama/llama2": 4096,
    ...,
}


[config] # in configuration.toml
model = "ollama/llama2"
model_turbo = "ollama/llama2"

[ollama] # in .secrets.toml
api_base = "http://localhost:11434/"
```
And this is the output I keep getting:

```
2024-04-17 16:11:29.179 | ERROR    | pr_agent.algo.utils:load_yaml:437 - Failed to parse AI prediction: mapping values are not allowed here
  in "<unicode string>", line 8, column 180:
     ... on in your `.pr_agent.toml` file:
                                         ^
2024-04-17 16:11:29.181 | INFO     | pr_agent.algo.utils:try_fix_yaml:459 - Failed to parse AI prediction after adding |-

2024-04-17 16:11:29.241 | INFO     | pr_agent.algo.utils:try_fix_yaml:488 - Successfully parsed AI prediction after removing 57 lines
2024-04-17 16:11:29.242 | ERROR    | pr_agent.tools.pr_reviewer:run:150 - Failed to review PR: 'str' object has no attribute 'get'
```

**Comment by mrT23** [comment]
as the error message says, remove the '...'

**Comment by ElonaZharri** [comment]
Thank you for your feedback. I did not have `...` in `__init__.py` Attached are a few screenshots of the setup:

<img width="769" alt="Screen Shot 2024-04-18 at 9 23 59 AM" src="https://github.com/Codium-ai/pr-agent/assets/16353934/0998e02c-3d82-4cb5-af41-54bbf10fc581">


<img width="648" alt="Screen Shot 2024-04-18 at 9 24 12 AM" src="https://github.com/Codium-ai/pr-agent/assets/16353934/a3cb7e82-c2e3-4a4d-9c6a-64d67444da89">

Run again this morning:
<img width="1053" alt="Screen Shot 2024-04-18 at 9 34 08 AM" src="https://github.com/Codium-ai/pr-agent/assets/16353934/8916a48b-c358-4b54-9e99-4bd10d89f998">

I agree, llama2 is weak, and I was wondering if I can use a custom llm provider, and use their API KEY token, instead of OpenAI.

**Comment by barnett-yuxiang** [comment]
[pr-agent-docs.codium.ai/usage-guide/additional_configurations/#changing-a-model](https://pr-agent-docs.codium.ai/usage-guide/additional_configurations/#changing-a-model)

**Comment by mrT23** [comment]
closing this issues, as it was discussed and solve in the Discord channel

**Comment by arvindanta** [comment]
@mrT23 can you share the link to the discord channel?

**Comment by arvindanta** [comment]
@ElonaZharri @mrT23 any suggestions for the error above?. Am also facing the same error with ollama/llama3.2 .

**Comment by mrT23** [comment]
llama3.2 is too weak to run properly code tasks, and returns an output that does not obey the prompt, so it cannot be parsed.

use better models

**Comment by arvindanta** [comment]
> llama3.2 is too weak to run properly code tasks, and returns an output that does not obey the prompt, so it cannot be parsed.
> 
> use better models

Got it, thanks. Any suggestions with local llms that might support this usecase ?
