### ISSUE TITLE
gpt-3.5-turbo context window is 16k

### ISSUE THREAD

**Issue by tacascer** [Codium-ai/pr-agent#874]
Hi there,

Thank you for maintaining this awesome tool!
I noticed that gpt-3.5-turbo's context window is now [16k](https://platform.openai.com/docs/models/gpt-3-5-turbo).

However, the max token specified for it is still [4k](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/__init__.py#L3)

Can we update the token limit for this model to 16k?

**Comment by mrT23** [comment]
you are welcome to open a PR for this

**Comment by tacascer** [comment]
Hey @mrT23 I've opened #880 for this.

Thank you!

**Comment by mrT23** [comment]
merged
