### ISSUE TITLE
Replace 👀  with ❤️ when response is completed

### ISSUE THREAD

**Issue by ntindle** [Codium-ai/pr-agent#882]
Having a finalized state would be awesome so I know its done processing at a glance

**Comment by mrT23** [comment]
by default we are doing something clearer than the icon - for each **persistent** tool (/review, /describe, ...) we are sending an `updated` message.
So I am not sure if there is a great need of also changing the icon

For example
https://github.com/Codium-ai/pr-agent/pull/872#issuecomment-2074131242

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/96bbda4b-b239-403a-a77c-38c2c33a2ba0)
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/e118140d-374f-48f8-8dc7-bfca6aced56a)

**Comment by mrT23** [comment]
In addition, the default, and by the far the most common, usage of PR-Agent is triggering the `/describe, /review, /improve` tools **automatically** when a new PR is opened, so the icons are relevant there
