### ISSUE TITLE
Have `/config` print the working config as well as all the options

### ISSUE THREAD

**Issue by ntindle** [Codium-ai/pr-agent#883]
I'm working on setting up Pro, but I am running into issues with the GH app agent reading my configs. Having it clarify where its reading a config from and what the final values it has for everything would be amazing

**Comment by mrT23** [comment]
@ntindle 
We understand that configuring pr-agent and ensuring the configurations are correct is harder than it should be today.

Your proposed feature is valid (show what are the actual configuration used), and we might implement it.

In addition, we plan to release in the coming week a PR-Agent **toolbar**, which will make understanding and configuring PR-Agent far more easier and intuitive (cc. @hussam789 )

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/3668081b-04f3-4ed0-8042-2218147e2ed7)
