### ISSUE TITLE
Add label base on pull request description.

### ISSUE THREAD

**Issue by borys-upco** [Codium-ai/pr-agent#885]
Hi,
I fallowed the instructions outlined in: https://pr-agent-docs.codium.ai/tools/custom_labels/#how-to-enable-custom-labels,
and added a new label:

|Label name|Description|
|-|-|
|`SQL Script`| `pr_agent: Adds or modifies SQL Queries`|

I'm hoping that the pr_agent will recognize and apply this label when the PR description (first comment made by the PR author) contains SQL scripts.

Is this feasible?

Thanks

**Comment by mrT23** [comment]
Labels are added mainly according to the **code changes**

If the PR code includes new SQL queries, the model will recognize this, and add the relevant label

**Comment by borys-upco** [comment]
I understand. Currently, SQL migrations are managed independently in our case. We include them in the PR description for reference.

**Comment by mrT23** [comment]
Try maybe a more specific label description, telling the model to focus on the PR 'Description' message (it is a part of the prompt)

Label name	Description
SQL Script	pr_agent: If the PR `Description` section discusses SQL changes _(or something more accurate...)_

**Comment by borys-upco** [comment]
Do I need to set `enable_custom_labels: true` in my YAML configuration for this GitHub job, or is it sufficient to create a label?

**Comment by borys-upco** [comment]
Thanks @mrT23 .
