### ISSUE TITLE
PR-Agent Chrome Extension: AWS CodeCommit

### ISSUE THREAD

**Issue by wahmedswl** [Codium-ai/pr-agent#891]
Hi!

PR-Agent Chrome Extension looks awesome, just saw the video. Is it only github native right now or other git providers are also supported? Primarily asking this question for AWS CodeCommit.

Thanks

**Comment by mrT23** [comment]
We do intend to release the Chrome Extension for more platforms.
But we prioritize according to popularity, so the next one will be Gitlab.

Realistically, for AWS CodeCommit we will probably need some contribution from the community to have the extension support it.
