### ISSUE TITLE
Azure DevOps output for suggestions is not aligned correctly in latest release

### ISSUE THREAD

**Issue by danstis** [Codium-ai/pr-agent#896]
The suggestions output in Azure DevOps has a table that is not aligned correctly, as per this example:
![image](https://github.com/Codium-ai/pr-agent/assets/2137928/9846d801-c3db-40e3-af67-a1939f08f754)

**Comment by mrT23** [comment]
Thanks, should be fixed now

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/c7b9a02d-745c-4096-9295-f7dcf5795601)

(azure is less robust for my HTML syntax problems than Github :-) )

**Comment by danstis** [comment]
Awesome, thanks again!
