### ISSUE TITLE
Update tiktoken to use gpt-4o

### ISSUE THREAD

**Issue by kazuki-ida** [Codium-ai/pr-agent#899]
Hi,

OpenAI announced GPT-4o today. So, tiktoken in pr-agent needs to be updated to version 0.7.0 in order to use this model, according to the tiktoken history.

Reference: https://github.com/openai/tiktoken/commit/9d01e5670ff50eb74cdb96406c7f3d9add0ae2f8

Thank you!

**Comment by mrT23** [comment]
thanks, i think this addressed that
https://github.com/Codium-ai/pr-agent/pull/901

**Comment by mrT23** [comment]
p.s
the tokenizer used by pr-agent is just for token estimation.
The actual tokenization process happens when you send the prompt to openAI, and they tokenized it on the cloud.

So its not really "mandatory". but its a good practice

**Comment by kazuki-ida** [comment]
That's right. 
Thank you for the quick response!

I will continue to use the wonderful product, pr-agent.
