### ISSUE TITLE
[Feature Request] Include AI model name in automated PR reviews

### ISSUE THREAD

**Issue by nataliezeller1** [Codium-ai/pr-agent#907]
Could we include the name of the AI model directly in the PR comments? 
This simple addition would enhance transparency and improve the monitoring of model performance across various projects.

**Comment by mrT23** [comment]
we are planing to introduce a new option next week, `show_relevant_config`, (for example --`pr_reviewer.show_relevant_config=true`), that will output an additional collapsible line with all the _relevant_ config fields for the tool.

One of them will be the model name.

**Comment by nataliezeller1** [comment]
Sounds great, thanks!

**Comment by mrT23** [comment]
see https://github.com/Codium-ai/pr-agent/pull/910
