### ISSUE TITLE
Provide a built docker image

### ISSUE THREAD

**Issue by fiws** [Codium-ai/pr-agent#917]
Would be nice if one could just use an existing official docker image instead of having to build it.

**Comment by mrT23** [comment]
we are nice people

https://hub.docker.com/r/codiumai/pr-agent/tags

https://pr-agent-docs.codium.ai/installation/locally/#using-docker-image

**Comment by fiws** [comment]
wow.. guess i did not look close enough :sweat_smile: 

Could it be that i actually still need to to this tho? The documentation suggests that i need to build my own if i want to use this with gitlab.

**Comment by mrT23** [comment]
There is a gitlab dcoker

`docker pull codiumai/pr-agent:gitlab_webhook`

If you are not using pr-agent-pro, you do need to **host** it yourself, and that's the focus of the instructions there

**Comment by fiws** [comment]
I think i need to cause we are using self hosted GitLab.

And according to the docs i also need to build the image then. It would be nice if one could just set everything as environment variable..

**Comment by mrT23** [comment]
This is what we provide currently.
you are welcome to try pr-agent-pro, where you wouldn't need anything

all the best

**Comment by fiws** [comment]
yea no worries. just trying to confirm that i do in fact need to build it...
