### ISSUE TITLE
Add logging message when files are filtered due to default extensions

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#927]
An info message is printed if a [user defined file filter](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/ignore.toml) ends up removing a file from a diff. This is not the case when a file is filtered out due to an ignored extension configured in [language_extensions.toml](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/language_extensions.toml).

I was experimenting with the PR agent and it was missing some of my changes. After debugging the code I found that `gradle` files are ignored by default. It would of been handy if some kind of log message was spit out on the console.

**Comment by mrT23** [comment]
sounds reasonable
https://github.com/Codium-ai/pr-agent/pull/931

<img width="1304" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/21198860/17ee3adf-de26-4321-a9f8-6be7f70fb030">
