### ISSUE TITLE
.secrets.toml file is ignored by .dockerignore

### ISSUE THREAD

**Issue by YuviGold** [Codium-ai/pr-agent#93]
Following https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#method-5-run-as-a-github-app steps 5 and 6, it guides to update a `pr_agent/settings/.secrets.toml` file to be used later on as part of the configuration files https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/config_loader.py#L10.

Though, when building the container image, the https://github.com/Codium-ai/pr-agent/blob/main/.dockerignore#L2 file makes `docker` to ignore this file as part of the build, causing the image to always fail with error

```
GitHub app ID and private key are required when using GitHub app deployment
```

**Comment by okotek** [comment]
The file should be made available to the container using a secret or other means, usually we won't want it in the docker image. The keys can also be set by environment variables, for example OPENAI.KEY.

**Comment by okotek** [comment]
https://github.com/Codium-ai/pr-agent/pull/96

**Comment by okotek** [comment]
![image](https://github.com/Codium-ai/pr-agent/assets/4869233/967f104d-8a83-4cb1-b869-ef25cf99b439)

**Comment by YuviGold** [comment]
Thanks! SGTM
