### ISSUE TITLE
[BUG] PR title not updated if using description markers

### ISSUE THREAD

**Issue by kacper-zylka** [Codium-ai/pr-agent#934]
Hi,

I'm using the GitHub action with the describe tool running when a PR is opened. I noticed that the PR title is never updated, even though I have `pr_description.generate_ai_title: true` and the action logs demonstrate that a `changes_title` is generated in the "Full_response" log. 

I looked into the code and it seems to be because [this method](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/tools/pr_description.py#L255C9-L255) `_prepare_pr_answer_with_markers` does not handle the `ai_title` at all, it simply returns back the original title. 

So in effect, if you have `pr_description.use_description_markers` set, the AI title will not be created. 

It seems like the fix would be to simply add [this block](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/tools/pr_description.py#L306-L313) to `_prepare_pr_answer_with_markers`?

Would you be able to fix this in the next release?

**Comment by mrT23** [comment]
This use case is not very logical my opinion.
Markers are used to control things manually. why would you want something as important as the PR header to be set automatically all the time, and still use markers ? 

In any case, that's my opinion. However, after thoroughly testing and making sure it works, I am still open to a PR for this issue from the community (you)

**Comment by kacper-zylka** [comment]
You're right, but then perhaps to give users more control it's better to introduce a new marker, say `pr_agent:title` and let users decide whether to use it or not? 

My use case is that I want the PR description to contain both autogenerated and developer-written content, and the PR title is not necessarily something that I need the developer to write.

Thanks for being open to PRs, sadly I don't have the capacity to work on this right now.
