### ISSUE TITLE
[FEATURE] Add GitHub Entreprise support

### ISSUE THREAD

**Issue by notbenjaminmur** [Codium-ai/pr-agent#943]
Hi !

I've try to install pr-agent, unfortunately it doesn't seem compatible with GitHub entreprise.
I've try to modify the code a little bit, everywhere github.com is hard-coded in the git_provider.
But you also use a github library for all the requests fetch, and the urls doesn't match the github entreprise urls...

Maybe it is in a roadmap somewhere ?

Thanks !

**Comment by mrT23** [comment]
GitHub enterprise is supported.
just edit this:

https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L140

**Comment by notbenjaminmur** [comment]
Thanks for your quick reply

I saw this configuration parameter
But when I change it, I have an error message "this is not a GitHub.com url"
Il the GitHub provider there is a GitHub.com check hard-coded

**Comment by benjaminmur** [comment]
Here: https://github.com/Codium-ai/pr-agent/blob/ab31d2f1f8bffa591e0b1fcd9bb176c2943700e6/pr_agent/git_providers/github_provider.py#L523

**Comment by mrT23** [comment]
ok. we support GitHub enterprise in `PR-agent-pro`, and you are welcome to try it there

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/1e05fec7-f775-4371-a5f7-642b352ab438)
