### ISSUE TITLE
YAML Fallback parsing method removes all generated content

### ISSUE THREAD

**Issue by NielsPichon** [Codium-ai/pr-agent#948]
## The issue

In the event where the generated response from the model is not valid YAML, the [last fallback method](https://github.com/Codium-ai/pr-agent/blob/83247cadec635aa896c5075235398508f5651497/pr_agent/algo/utils.py#L318) may end up removing the entire generated response. 

## Suggested behaviour
I think a more appropriate solution here would be to return the following instead:

```
return {'review': f'The following answer could not be properly parsed and formatting might be broken:\n\n{'\n'.join(response_text_lines}'}
```

I used the `review` key here, such that it will allow the rest of the pr_reviewer agent to work properly.

I understand this might result in a less polished experience but I think this would be more appropriate than no answer from the model at all.
 
## How to reproduce

Example response I got which triggered this behaviour:

```
"\nAI response:\nHere is the suggested review output in YAML format:\n\n```\n| Review:\n  - foo \n -bar\n```\n\nPlease note that this review is not exhaustive and you should consider reviewing the code for other potential issues as well.\n"
```

Feeding it to `pr_agent.algo.utils.load_yaml` returns:

```
{'AI response': None,
 'Here is the suggested review output in YAML format': None}
```

**Comment by mrT23** [comment]
I bet 97% you worked with a non-GPT model, right ?

PR-Agent requires a good code model, like GPT4 or Claude, to produce good results. It has a very hard input - PR code diff.

The response you presented is bad, and does not obey the prompt instructions ("give YAML, and nothing else"). It is bad, not just because of the non-yaml first line, but also because it doesn't have a closing ``` brackets, so how would we know if the model didn't add unwanted stuff also in the end ? And there could be also brackets in the middle, for example when equation code-diff.

In general, I don't think your model will produce good results in terms of real-life usage. It does not obey the prompt

**Comment by NielsPichon** [comment]
Indeed this is `ollama/llama3` output. 
On that said, I still think there is value in being able to retrieve the raw prediction in case parsing fails. On that said I see how this might affect the experience of the repo users.

**Comment by mrT23** [comment]
llama3 (8B !) is a terrible mode for code.
You can use it for games with PR-Agent, and you did.

In [cover-agent](https://github.com/Codium-ai/cover-agent) we did add the post-processing you are talking about, and you can use that as inspiration if you wish to fix it locally. all the best
https://github.com/Codium-ai/cover-agent/blob/main/cover_agent/utils.py#L122
