### ISSUE TITLE
'Preparing review...' comment

### ISSUE THREAD

**Issue by mirkobertone** [Codium-ai/pr-agent#957]
Hello,
I setup pr-agent docker in my BitBucket pipeline. It always write a commit in the Jira associated task that is quite annoying. Is there any configuration to disable it?
I share a screenshot
![image](https://github.com/Codium-ai/pr-agent/assets/39023403/e5ec9382-e706-45b4-acde-532da3513bad)

**Comment by mrT23** [comment]
you can open a PR to make this temporary comment configurable

**Comment by mrT23** [comment]
This issue was addressed. auto commands wont show this message anymore

**Comment by alessio-locatelli** [comment]
@mrT23 But what is the point of this `Preparing review...` comment even if it will be removed? IMHO, it is useless and only gives extra noise. I believe this was assumed to be an indicator that the review process has been started, but it can be obvious from CI and the review process is too short to post a dedicated comment about the start of the process. Does anyone really want to maintain a feature that people are looking to disable right away? What is your opinion on removing this `Preparing review...` completely?


PS: For anyone looking for a temporary workaround, use `CONFIG__is_auto_command=true`.
