### ISSUE TITLE
Add section to pr-agent-settings toml file to ingore repos

### ISSUE THREAD

**Issue by lmtyler** [Codium-ai/pr-agent#968]
Request feature to have section in .pr_agent.toml in the pr-agent-settings repo to allow skipping repos

say I have the following repos

- repo1
- repo2
- repo3
- pr-agent-settings

add a section in the .pr_agent.toml so that repo2 does not get the global settings, without having to create an override specifically in repo2

thus global settings only apply to repo1 and repo3

**Comment by mrT23** [comment]
I don't see it as something that is more convenient than the current degrees of freedom.
The most logical thing to do is a global configuration, that apply to all, and a local configuration, if you want to overide it.
