### ISSUE TITLE
Unable to run PR Agent with GPT 3 Key

### ISSUE THREAD

**Issue by ShivamParasharMT** [Codium-ai/pr-agent#977]
I have a GPT 3 key that I want to use with PR Agent but it keeps calling the GPT 4 model which results in an error.

Agent Setup Info
name: PRAgent
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

.pr_agent.toml config
[config]
model = "gpt-3.5-turbo-0125"
model_turbo = "gpt-3.5-turbo"

PR Agent error
{"text": "Failed to generate prediction with gpt-4-turbo-2024-04-09: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/litellm/main.py\", line 283, in acompletion\n    response = await init_response\n  File \"/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py\", line 439, in acompletion\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py\", line 424, in acompletion\n    response = await openai_aclient.chat.completions.create(\n  File \"/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py\", line 1330, in create\n    return await self._post(\n  File \"/usr/local/lib/python3.10/site-packages/openai/_base_client.py\", line 1725, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"/usr/local/lib/python3.10/site-packages/openai/_base_client.py\", line 1428, in request\n    return await self._request(\n  File \"/usr/local/lib/python3.10/site-packages/openai/_base_client.py\", line 1519, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-2024-04-09` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py\", line 145, in chat_completion\n    response = await acompletion(**kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 3181, in wrapper_async\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 3017, in wrapper_async\n    result = await original_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/litellm/main.py\", line 296, in acompletion\n    raise exception_type(\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 8180, in exception_type\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 6943, in exception_type\n    raise NotFoundError(\nlitellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-2024-04-09` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/pr_agent/algo/pr_processing.py\", line 275, in retry_with_fallback_models\n    return await f(model)\n  File \"/app/pr_agent/tools/pr_reviewer.py\", line 159, in _prepare_prediction\n    self.prediction = await self._get_prediction(model)\n  File \"/app/pr_agent/tools/pr_reviewer.py\", line 181, in _get_prediction\n    response, finish_reason = await self.ai_handler.chat_completion(\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/__init__.py\", line 314, in iter\n    return fut.result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py\", line 146, in chat_completion\n    except (openai.APIError, openai.Timeout) as e:\nTypeError: catching classes that do not inherit from BaseException is not allowed\n\n", "record": {"elapsed": {"repr": "0:00:07.348074", "seconds": 7.348074}, "exception": null, "extra": {}, "file": {"name": "pr_processing.py", "path": "/app/pr_agent/algo/pr_processing.py"}, "function": "retry_with_fallback_models", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 277, "message": "Failed to generate prediction with gpt-4-turbo-2024-04-09: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/litellm/main.py\", line 283, in acompletion\n    response = await init_response\n  File \"/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py\", line 439, in acompletion\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py\", line 424, in acompletion\n    response = await openai_aclient.chat.completions.create(\n  File \"/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py\", line 1330, in create\n    return await self._post(\n  File \"/usr/local/lib/python3.10/site-packages/openai/_base_client.py\", line 1725, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"/usr/local/lib/python3.10/site-packages/openai/_base_client.py\", line 1428, in request\n    return await self._request(\n  File \"/usr/local/lib/python3.10/site-packages/openai/_base_client.py\", line 1519, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-2024-04-09` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py\", line 145, in chat_completion\n    response = await acompletion(**kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 3181, in wrapper_async\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 3017, in wrapper_async\n    result = await original_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/litellm/main.py\", line 296, in acompletion\n    raise exception_type(\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 8180, in exception_type\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/litellm/utils.py\", line 6943, in exception_type\n    raise NotFoundError(\nlitellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-2024-04-09` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/pr_agent/algo/pr_processing.py\", line 275, in retry_with_fallback_models\n    return await f(model)\n  File \"/app/pr_agent/tools/pr_reviewer.py\", line 159, in _prepare_prediction\n    self.prediction = await self._get_prediction(model)\n  File \"/app/pr_agent/tools/pr_reviewer.py\", line 181, in _get_prediction\n    response, finish_reason = await self.ai_handler.chat_completion(\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/__init__.py\", line 314, in iter\n    return fut.result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py\", line 146, in chat_completion\n    except (openai.APIError, openai.Timeout) as e:\nTypeError: catching classes that do not inherit from BaseException is not allowed\n", "module": "pr_processing", "name": "pr_agent.algo.pr_processing", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140241377618816, "name": "MainThread"}, "time": {"repr": "2024-06-07 08:44:40.791554+00:00", "timestamp": 1717749880.791554}}}

Which indicates its still using GPT 4 and not using the configured 3 model.

**Comment by mrT23** [comment]
i dont see anywhere in the logs that a configuration file was read. ("Applying repo settings")


triple and quadropule check to you have followed the instructions:
https://pr-agent-docs.codium.ai/usage-guide/configuration_options/#local-configuration-file
you can also try to give parameters via the env:
https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-action

since this is self-deployment, we are limited in our ability to understand what went wrong with your specific deployment.

**Comment by barnett-yuxiang** [comment]
@ShivamParasharMT Or you can delete .sercert.toml, ` cp it` and fill in the OpenAI API key and GitHub token.

Or you can print out the detailed log troubleshooting, or paste it here.

```
pr_agent/settings/configuration.toml
verbosity_level=2

pr_agent/cli.py
log_level = os.environ.get("LOG_LEVEL", "DEBUG")
