### ISSUE TITLE
Suggestions match existing code

### ISSUE THREAD

**Issue by dbmessina** [Codium-ai/pr-agent#979]
The suggestions made for our Flutter app are very frequently to add code that already exists. Here is an example where a const constructor is recommended despite already having one:

![image](https://github.com/Codium-ai/pr-agent/assets/96109732/273b5b88-540c-4b87-b6db-3c1d1ce0cc69)

**Comment by mrT23** [comment]
1. mistakes can happen. its AI

2. the suggestion got a low score (6). Important suggestions are above ~7-8. If you prefer only major-super-sure suggestions, enable suggestions only above a threshold:
https://pr-agent-docs.codium.ai/tools/improve/#configuration-options
I do recommend this option for Bitbucket. Bitbucket interface is so old and outdated, that it does not support even simple graphics like collapsible. So we have to send these very noisy inline code suggestions, and suddenly, every non-important or somewhat mistaken suggestion is amplified. with a normal [interface](https://github.com/Codium-ai/pr-agent/pull/978#issuecomment-2173951665), the "price" of a non-relevant suggestion is much lower


3. The 'extra instructions' field of each tool should be used exactly for this case: state what do you want to emphasize or discourage in the suggestions: (extra_instructions: "make sure that in flutter not to suggest code that already exists ")


4. You have not shared details about your deployment. I really hope you use GPT4 and not an inferior model. If you are a pr-agent-pro user and can consistently reproduce a bad suggestion, send a URL of an example PR where you were able to reproduce it, and we can try to look at the logs.

**Comment by davidparry** [comment]
> 1. mistakes can happen. AI is not perfect
> 2. the suggestion got a low score (6). Important suggestions are above ~7-8. If you prefer only major-super-sure suggestions, enable suggestions only above a score threshold:
>    https://pr-agent-docs.codium.ai/tools/improve/#configuration-options
>    I do recommend this option for Bitbucket. Bitbucket interface is so old and outdated, that it does not support even simple graphics like collapsible. So we have to send these very noisy inline code suggestions, and suddenly, every non-important or somewhat mistaken suggestion is amplified. with a modern [interface](https://github.com/Codium-ai/pr-agent/pull/978#issuecomment-2173951665), the "price" of a non-relevant suggestion is much lower
> 3. The 'extra instructions' field of each tool should be used exactly for this case: state what do you want to emphasize or discourage in the suggestions: (extra_instructions: "make sure that in flutter not to suggest code that already exists ")
> 4. You have not shared details about your deployment. I really hope you use GPT4 and not an inferior model. If you are a pr-agent-pro user and can consistently reproduce a bad suggestion, send a URL of an example PR where you were able to reproduce it, and we can try to look at the logs.

This is for Lexipol an Enterprise customer the PR https://bitbucket.org/lexipol/cordico-flutter/pull-requests/368 that shows the consistent suggestion.

**Comment by dbmessina** [comment]
Here is another example of the PR Agent suggesting code that is already there:

![image](https://github.com/Codium-ai/pr-agent/assets/96109732/ab4a87a1-6a45-4800-bc02-3e3e76d9f482)

**Comment by mrT23** [comment]
I gave a clear and detailed answer.
If the (easily spottable) mistakes happens once every ~1-2 weeks, then its well above a reasonable threshold for an AI system
