### ISSUE TITLE
Missing support for private certificate authorities

### ISSUE THREAD

**Issue by ocroz** [Codium-ai/pr-agent#997]
The docker command fails to get local issuer certificate, because...
Our GitLab server is signed by our company Root CA and Signing CA which the pr-agent doesn't know.

How can we make the pr-agent to trust our company Root CA and Signing CA ?

Thanks for your help

**Comment by ocroz** [comment]
OK, I found a workaround, reusing the `cacerts` of my local `ubuntu` system, as `pr-agent` is using `python3`.

```bash
cacerts=/etc/ssl/certs/ca-certificates.crt
docker run -it --rm -v $cacerts:$cacerts:ro -e REQUESTS_CA_BUNDLE=$cacerts ...
```

**Comment by samuele-ruffino96** [comment]
It'd be a bit less cumbersome having a CLI param to skip TLS verify :smile:
